README.md
Running the analysis without explicitly setting NB_BOUNDARY_BUFFER can lead to a confusing scenario where you end up with no linked census blocks, and all of the statistics in the `neighborhood_overall_scores` table are zero.
=> Add NB_BOUNDARY_BUFFER to README

Vagrantfile, deployment/ansible/roles/pfb.analysis/tasks/main.yml
Installs GNU `parallel` and ups the default amount of CPUs in the `Vagrantfile` to 8.
Allows https://github.com/azavea/pfb/pull/11 to run.
Connects #44
=> Prepare VM for parallel processing

README.md, Vagrantfile
Switch to ansible-local provisioning so that the VM can be used easily on all three major OSs. 
`vagrant destroy` then `vagrant up --provision`. The VM should still provision successfully, using ansible-local instead of ansible.
This is untested on Windows ATM. Will attempt to test on Windows over the weekend at home and update as necessary.
=> Switch to ansible-local provisioning

README.md
Just fixing a typo I noticed in the docs as I was setting up the VM.
=> Fix reference to ./scripts/setup in README.md

Vagrantfile, deployment/ansible/pfb.yml, deployment/ansible/roles/pfb.env/defaults/main.yml, deployment/ansible/roles/pfb.env/tasks/main.yml, docker-compose.yml, src/django/pfb_network_connectivity/settings.py
In order to separate development resources on AWS (such as S3 buckets), we need to pass the developer's username from their host machine through the vagrant VM, into the docker container, and finally into the django instance.
This pull request accomplishes this by passing the username from the host environment to Ansible through the `Vagrantfile`. Ansible writes this to `/etc/environment` as the `DEV_USER` variable. When `docker-compose up` is run, this environment variable is passed into the container as specified in `docker-compose.yml`.
* Reprovision
* `docker-compose up`
* While `docker-compose` is running, `docker exec -it vagrant_django_1 /bin/bash`
* `./manage.py shell`
* `from django.conf import settings; print settings.DEV_USER`
* Ensure your username is printed
Connects #61
=> Add DEV_USER environment variable to separate AWS dev environments

docs/architecture/adr-0004-asynchronous-task-queue-2.md
Adds ADR0004 which describes an alternative method of async task queue management using [AWS Batch](https://aws.amazon.com/documentation/batch/). 
Supersedes [ADR0003](https://github.com/azavea/pfb-network-connectivity/blob/develop/docs/architecture/adr-0003-asynchronous-task-queue.md).
Taking suggestions for a different name for this ADR.
=> Add ADR0004: Asynchronous Task Queues 2

Jenkinsfile, deployment/README.md, deployment/ansible/group_vars/all, deployment/ansible/pfb.yml, deployment/ansible/roles.yml, deployment/terraform/alarms.tf, deployment/terraform/app.tf, deployment/terraform/cloud-config/ecs-user-data.yml, deployment/terraform/container-service.tf, deployment/terraform/database.tf, deployment/terraform/dns.tf, deployment/terraform/firewall.tf, deployment/terraform/iam.tf, deployment/terraform/network.tf, deployment/terraform/provider.tf, deployment/terraform/storage.tf, deployment/terraform/task-definitions/app.json, deployment/terraform/task-definitions/management.json, deployment/terraform/task-definitions/nginx.json, deployment/terraform/variables.tf, docker-compose.test.yml, docker-compose.yml, scripts/cipublish, scripts/infra, src/django/pfb_network_connectivity/settings.py, src/django/pfb_network_connectivity/urls.py, src/django/requirements.txt, src/nginx/etc/nginx/nginx.conf
Adds the terraform tooling necessary to deploy the staging environment to AWS.
Not much there, just the healthcheck and an API you can't log into yet because I haven't run migrations, which I will do in a bit.
https://staging.pfb.azavea.com
Peripheral stuff I had to add:
- django-watchman for the healthcheck endpoint
- Fixup settings.py to properly set things based on the actual ENV variables
- Remaining scripts to rule them all
- Update Jenkinsfile (currently untested)
After following instructions to set env properly in deployment/README.md, a `./scripts/infra plan` should show no assets to update
=> Staging Terraform deployment

README.md, scripts/cibuild, scripts/cipublish
Builds and pushes the pfb-analysis container, formerly tagged as `pfb` to a new `pfb-analysis` ECR endpoint.
I renamed the `pfb` container in the README to keep naming conventions consistent.
Log into AWS and check to ensure that a tagged container exists in the pfb-analysis registry.
=> Push analysis container to ECR repository on CI build

pfb-analysis/scripts/entrypoint.sh, pfb-analysis/scripts/run_connectivity.sh, pfb-analysis/scripts/setup_database.sh
A few tiny tweaks, plus...
Adds some configuration commands to setup_database.sh that:
- per issue #90, increases work_mem (by a lot--4mb to 4gb)
- per issue #76, makes checkpoints happen less frequently
Note that this used to be controlled by `checkpoint_segments` but is
now (as of Postgres 9.6) mainly a function of `max_wal_size`.
- Related to checkpoints, I also increased `checkpoint_completion_target`
which should have the effect of reducing write bottlenecks at the cost
off less robust crash recovery (which I don't think we care much
about in this context)
=> `work_mem` and checkpoint-related database settings

pfb-analysis/import/import_jobs.sh, pfb-analysis/import/import_neighborhood.sh, pfb-analysis/import/import_osm.sh, pfb-analysis/scripts/entrypoint.sh, pfb-analysis/scripts/import.sh
These are changes I made in the course of working on PR #107 because I got tired of waiting for the downloads over and over (the PA tabblock file is 247MB...), and they seem useful enough and harmless enough to commit.
For the jobs and blocks files, this just makes it so that if the exact filename the script is looking to download already exists in the `data` directory, it will use that.  If it doesn't, it acts normally.  It doesn't copy the script once downloaded into the data dir to be used for next time, just uses it if it's there, so to take advantage of this you have to download it manually (or copy it out of a container that downloaded it, but that's tricky because it gets deleted as soon as it's been used...).
For the OSM file, since it's based on the boundary rather than being …
=> Enable local copies of downloads

pfb-analysis/import/import_neighborhood.sh
I noticed we're not building a spatial index on the neighborhood or the census tables when we import them. It's possible these are being built elsewhere, but it seems easiest to build them on import with the -I flag.
=> Add -I flag to shp2pgsql calls to build spatial index on tables

pfb-analysis/import/import_jobs.sh, pfb-analysis/import/import_neighborhood.sh, pfb-analysis/scripts/entrypoint.sh, pfb-analysis/scripts/export_connectivity.sh
Connects #80.
Adds export_connectivity.sh to entrypoint.sh, using `NB_OUTPUT_DIR`.
Notes:
- It doesn't define a default nor does it raise an error at the beginning of the run if the variable isn't set. This could be a pain, since we could run analyses and then end up not getting the results, but on the other hand once we've built further tooling around running the analysis it might not be a problem in practice.  In any case there are ways to get into an image and re-run the export if necessary.
- It does, however, run `mkdir -p NB_OUTPUT_DIR`, so if you give it a path that doesn't exist but does make sense, it create and use that directory (regular mkdir throws an error if a directory already exists, but with `-p` it's fine)
- This branch also includes a change to `import_neighborhood.sh` …
=> Run export connectivity in docker analysis

README.md, pfb-analysis/Dockerfile, scripts/clean-analysis-volumes
Adds helper script to easily cleanup old pfb-analysis docker containers/volumes that take up large amounts of the limited disk space available to the VM.
```
vagrant@pfb-network-connectivity:/vagrant$ ./scripts/clean-analysis-volumes
This script will delete the following containers:
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                          PORTS               NAMES
8208464a6078        pfb-analysis-label   "/bin/sh -c /pfb/scri"   3 minutes ago       Exited (0) About a minute ago                       focused_sammet
Are you sure? [y/N] y
8208464a6078
vagrant@pfb-network-connectivity:/vagrant$
vagrant@pfb-network-connectivity:/vagrant$
vagrant@pfb-network-connectivity:/vagrant$ docker ps -a --filter "label=type=pfb-analysis" …
```
=> Add helper script to clean up old pfb-analysis docker containers/volumes

deployment/README.md, docker-compose.yml, scripts/cibuild, scripts/update, src/nginx/etc/nginx/conf.d/default.conf
Connects #95.
Most of the steps for that issue were done in PR #86, but it wasn't actually working.  I believe that's because of the `volumes:` mapping, which only makes sense in development but was probably mapping a nonexistent directory over top of the one inside the container.  At least that's the theory.  Anyway, using that volume mapping only makes sense in local development but isn't necessary or particularly useful, so this just removes it.
Also:
- I also made some changes to `scripts/update` and `scripts/cibuild` to ensure that the static files built by the AngularJS site are up to date and where they're supposed to be when they get copied into the nginx container's directory, and that the nginx container doesn't get built until that has happened.
- And a small tweak to the …
=> Serve AngularJS site with nginx

Jenkinsfile
Missed a use of `PFB_AWS_ECR_ENDPOINT in `./scripts/infra`. This adds those credentials to the appropriate step in the Jenkinsfile.
See http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/job/develop/32/ for a successful run against develop with this change applied.
=> Provide PFB_AWS_ECR_ENDPOINT to infra

pfb-analysis/Dockerfile, pfb-analysis/import/import_jobs.sh, pfb-analysis/import/import_neighborhood.sh, pfb-analysis/scripts/entrypoint.sh, pfb-analysis/scripts/export_connectivity.sh, src/django/pfb_analysis/models.py
Adds S3 uploading and downloading.  Requires that `AWS_STORAGE_BUCKET_NAME` be set.  In development, `AWS_PROFILE` must also be set and the `.aws` directory must be mounted in the container.
The new bits:
- Given `PFB_SHPFILE_KEY`, downloads the boundary file from the given S3 key, unzips it, and sets the value of `PFB_SHPFILE`.  (If `PFB_SHPFILE` is also set, this will override it.)
- When finished, zips up the results and uploads to `{AWS_STORAGE_BUCKET_NAME}/results/{PFB_NEIGHBORHOOD_NAME}.zip`.  (`PFB_NEIGHBORHOOD_NAME` is now required by the export.)
- Adds an S3 clause to the "reuse big downloads" logic in `import_neighborhood.sh` and `import_jobs.sh`. They'll look first in the local `/data/` directory, then in `{AWS_STORAGE_BUCKET_NAME}/data/`, then do the download.
This doesn't do …
=> Use S3 for analysis files

README.RUNNING.md, README.md, pfb-analysis/scripts/entrypoint.sh, scripts/run-local-analysis
Connects #120.
The details of running the analysis change frequently and the documentation is scattered.  This adds a script, `scripts/run-local-analysis` to encapsulate the defaults so we don't have to include so much boilerplate in all our examples that quickly goes out of date.
It also moves the "Running the analysis" section into its own README and changes it to use Boulder (mainly because Cambridge requires overriding the input SRID).
This should replace Issue #10 and make the command examples in various other issues (e.g. #128) no longer necessary.  It should also make it easier to keep the behavior and parameters of the analysis well documented.
~~There are multiple TODOs here, but I wanted to put something up to facilitate the conversation in connection with the discussion on PR …
=> Move and modify 'Running the analysis' documentation

deployment/README.md, deployment/aws-batch/job-definitions/pfb-analysis-run-job.json, deployment/terraform/batch-container-service.tf, deployment/terraform/cloud-config/ecs-batch-user-data.yml, deployment/terraform/variables.tf, src/django/pfb_analysis/models.py
Our analysis jobs require large amounts of scratch space for the postgresql data dir. This required switching to unmanaged CE's so that we can mount the ephemeral storage space provided by the `i3` EC2 instance class. 
Remaining TODOs:
Left some comments in the diff for things I'm unsure of how to handle.
The Jenkins build is currently disabled so that merges to develop do not delete the extra ECS stack that was deployed via this branch. Re-enable Jenkins before merging.
#118 is no longer necessary as we're mounting an external docker volume
Pull down this branch, start your local Django instance, and then run the following commands:
```
user = PFBUser.objects.first()
from django.core.files import File
boundary_file = File(open('/data/gtown_westside.zip'))
org = …
```
=> Switch to Batch Unmanaged Compute Environment

.gitignore, common.yml, scripts/cibuild, scripts/cipublish, src/django/pfb_network_connectivity/settings.py, src/nginx/Dockerfile, src/nginx/etc/nginx/conf.d/default.conf
Updates the Nginx/Django configuration to compile and serve static files from a separate directory in the nginx container. 
```
export GIT_COMMIT=9051463
./scripts/cibuild
docker-compose -f docker-compose.yml -f docker-compose.test.yml up nginx
```
Navigate to http://localhost:9200/api/ which will serve static files from nginx. To prove this is the case, you can `rm -rf src/nginx/srv/static/*` and then request the same URL.
The staging site will stop properly serving the static assets if another branch is merged to develop before this one.
Connects #87
=> Serve Django static files from nginx container

deployment/ansible/group_vars/all.example
Removes some variables from `group_vars/all.example` that became obsolete when the analysis was dockerized.  ~~Also adds a comment to note that the postgres group_var overrides don't affect the analysis but are set up to match the versions used by the analysis, for the sake of not adding potential confusion to the project by running two different versions of postgres.~~
Connects #124.
=> Clean out unnecessary group_vars

deployment/terraform/cloud-config/ecs-batch-user-data.yml
The fs_setup cloud-config directive was not properly mounting the i3 instance family ephemeral storage, discovered when our docker volume mount point mounted directly on the 8Gb root volume and a job ran out of disk space.
See https://bugs.launchpad.net/cloud-init/+bug/1672833 for a detailed breakdown of why this solution is necessary
Mounted disks after boot:
From /var/log/cloud-init-output.log:
Nothing really to test, with this configuration applied via `./scripts/infra plan && ./scripts/infra apply` the ephemeral device is properly mounted at the expected location as evidenced in the screenshots above.
Connects #163
=> Manually mount i3 instance family ephemeral storage

README.RUNNING.md
This should have been part of PR #167.  Also deletes a line about
run-local-analysis mapping the data directory, since as of PR #179
that's now specified in docker-compose.yml.
=> Update README.RUNNING.md for NB_MAX_TRIP_DISTANCE

deployment/terraform/app.tf
Fixes container image URL for the management task definition.
Addresses the issue in your PR where you're unable to properly run management commands due to an invalid container image tag.
Didn't deploy, this is untested, but the name now matches the one used for the app task, and there are no other instances of the string `management_url` in the terraform code.
=> Fixup management container image url

deployment/terraform/batch-container-service.tf, deployment/terraform/cloud-config/ecs-batch-user-data.yml, deployment/terraform/variables.tf
More aggressive removal of containers prevents us from filling up the root volume with stopped containers when many analysis jobs are run at once in a batch
Nothing really. Change is deployed on current staging batch container instance.
Connects #170
=> Tweak ECS agent image cleanup on batch stack

deployment/terraform/app.tf, src/django/pfb_analysis/management/commands/run_analysis_job.py, src/django/pfb_analysis/models.py, src/django/pfb_network_connectivity/settings.py
Since we can't run local development jobs on the staging AWS Batch cluster after PR #179, provides two interim options:
- A management command to run a job from ECS "Run new task".  Requires that the neighborhood you want to run already exist.
- To make it easier to run the analysis locally, it prints the command that will do it, complete with job ID and shapefile URL.  The more complete version of this approach, where the django container actually connects to the host Docker daemon and starts the analysis job, seems like it would add a lot more work for not that much gain.  Indeed, opt-in (i.e. you have to copy the command and run it to make it go rather than having to cancel the run if you don't want it) seems like possibly the right choice for local development.
Local, assuming you …
=> Add options for running development jobs

scripts/cibuild
Not removing this was causing incremental disk space usage and a bunch of leftover exited containers on the CI server
@azavea/operations
=> Remove angularjs build container after rsync

src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.controller.js, src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.html, src/angularjs/src/app/analysis-jobs/create/module.js, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/analysis-jobs/module.js, src/angularjs/src/app/components/filters/analysis-job-filter.directive.js, src/angularjs/src/app/components/neighborhoods.service.js, src/angularjs/src/app/index.route.js, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/pagination.py
Adds a "Run Analysis" view to the management app, for kicking off analysis jobs.
- I added an `all` route to the neighborhoods endpoint because the droplist in this view and in the filter on the list view shouldn't be paginated.  Neighborhoods aren't very big, so I didn't bother to limit the fields returned, but we could if it seems laggy at all.
- I added a `neighborhood_label` SerializerMethodField to AnalysisJob so that we can show the label in the list.  Including the whole neighborhood with the job is pretty easy for GET requests but makes saving a bit more complicated, and I think label and ID (which is already there, in the `neighborhood` field) are all we're likely to need.
With the AngularJS app running, go to http://localhost:9301/#/analysis-jobs/ and click 'Run Analysis'.  Pick …
=> Create analysis job view

src/django/pfb_analysis/management/commands/update_status.py, src/django/pfb_analysis/models.py, src/django/pfb_analysis/views.py
Adds API view to cancel in progress AnalysisJobs
I chose to do no error handling of exceptions fired by the AnalysisJob.cancel method. Theoretically, we could handle errors that happen within the boto calls, but the only HTTP status to return that _maybe_ makes more sense than the default 500 error is 503. And I'm not sure its worth it at this point to account for that.
Get a token from http://localhost:9200/#/users/edit/:userid/ by clicking the 'refresh token' button.
Trigger a new analysis job via API views, curl, postman, etc. Note the new job's ID.
POST http://localhost:9200/api/analysis_jobs/:jobid/cancel/ via curl, postman, etc. The response should be the analysis job object, with `status: 'CANCELLED'`.
Closes #213
=> Add API view to cancel AnalysisJobs

src/django/pfb_analysis/models.py, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py
Adds an API view to give the user access to all available results from a single AnalysisJob.
Accessible at `/api/analysis_jobs/:jobId/results/`. If AnalysisJob.status != COMPLETE, then the endpoint returns 404 Not Found.
Will wait to merge until I can add the number of census blocks in the analysis to this endpoint, which is being added separately in #183 
Run a local job to completion via the AnalysisJob.run() method. Then query the results endpoint mentioned above, and you should be able to view the overall scores and download the related results files.
Closes #211
=> Add API view for AnalysisJob results

src/analysis/import/import_osm.sh
See #216 and discussion in the linked osm2pgrouting issue for a detailed writeup.
This simply updates osmconvert to be called with the appropriate flag to avoid leaving broken node refs in the converted OSM data.
After rebuilding the analysis container in the VM with `docker-compose build analysis`, run a job that makes use of a Mapzen Metro Extract. Example:
```
PFB_OSM_FILE_URL=https://s3.amazonaws.com/metro-extracts.mapzen.com/philadelphia_pennsylvania.osm.bz2 AWS_PROFILE=pfb ./scripts/run-local-analysis https://s3.amazonaws.com/test-pfb-inputs/germantown/gtown_westside.zip pa 42
```
Verify that while running the job, no lines like this:
```
Reference nd=4719271035 has no corresponding Node Entry (Maybe Node entry after Reference?)
```
are in the job output.
Closes #216
=> Drop broken refs in osmconvert when clipping via bbox

src/analysis/scripts/export_connectivity.sh, src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.controller.js, src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.html, src/angularjs/src/app/analysis-jobs/detail/module.js, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/analysis-jobs/module.js, src/angularjs/src/app/components/analysis-jobs/analysis-jobs.service.js, src/angularjs/src/app/index.route.js, src/django/pfb_analysis/models.py, src/django/pfb_analysis/views.py
Adds a functional (but not super pretty) AnalysisJob detail view to the admin UI. 
User can see all properties of the AnalysisJob, can refresh the view to check for updates, and can cancel an in progress job. 
Didn't get fancy with the cancel button. If a job is cancellable it'll cancel, otherwise silently do nothing. I think it's fine for now.
Same with dressing up the rows, or trying to neatly format text. Don't see value in it yet, easy to clean up later.
I included links in the data section to all files requested for download in #157, including a zipped connected_census_blocks.csv
Start AnalysisJob from UI in development. Go to detail page. Cancel it, to prove that works. Start another job. Run it via console. Go to detail page for that job and click refresh while job is in progress …
=> Angular AnalysisJob detail view

src/django/requirements.txt
Whomp whomp. Set up SES emails but never added the dependency on `django-amazon-ses`. This does so. Container instance is already configured via `iam.tf` with the required instance profile permissions `ses:SendRawEmail`.
Trivial, merging.
=> Add django-amazon-ses dependency for email backend

src/django/pfb_analysis/models.py
I converted results path from a hard-coded string in a few places to a
method on AnalysisJob, but got the syntax wrong when I changed
`_s3_url_for_result_resource` for the new setup.
=> Fix join syntax in results URLs method

src/django/pfb_analysis/filters.py, src/django/pfb_analysis/functions.py, src/django/pfb_analysis/models.py, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/filters.py
Adds "overall score" and "latest updated" sorting and filtering to the AnalysisJobs endpoint.
- Latest updated. Sorting by `created_at` already worked, but with the addition of `latest=True`, it now works as a "neighborhoods by last analysis run" endpoint: http://localhost:9200/api/analysis_jobs/?latest=True&ordering=-created_at
- Highest rated: http://localhost:9200/api/analysis_jobs/?latest=True&ordering=-overall_score
- Lowest rated: http://localhost:9200/api/analysis_jobs/?latest=True&ordering=overall_score
- Alphabetical by neighborhood: http://localhost:9200/api/analysis_jobs/?latest=True&ordering=neighborhood__label (note the double-underscore.  the `neighborhood_label` field in the results is a MethodField added by the serializer, so not sortable)
~Issue #242 calls for "Last …
=> Add score and latest-updated sorting to AnalysisJob endpoint

scripts/run-local-analysis
Use of `./scripts/run-local-analysis` was not passing through the PFB_S3_RESULTS_PATH variable, leading to files being uploaded to the root path of the specified S3 bucket (not so good).
Discovered while testing #269
=> Ensure PFB_S3_RESULTS_PATH is properly passed to local container

deployment/terraform/iam.tf
Email permissions are needed by the EC2 instance to properly send user emails. These were quickfixed earlier on by adding the necessary permissions in the console. Now the same permissions are codified in Terraform
I _believe_ I made these changes in an acceptable way, as an inline policy for both ECS/EC2. Permission seems to be necessary on both. 
Can checkout branch and run `./scripts/infra plan` to verify no permissions changes in the plan, the changes in the PR are live in the staging environment.
Closes  #238
=> Codify SES Send Email permissions in Terraform

src/tilemaker/entrypoint.sh, src/tilemaker/styles/neighborhood_ways_style.xml
Updates the styling for the stress score tiles to
- only rely on the `SEG_STR` scores (formerly it also looked at `INT_STR`)
- display the `FT` and `TF` scores separately by offsetting them in opposite directions.
- I also changed the tile generation command to produce some output, rather than none, as it was doing, or tens of thousands of lines, as it was doing before that.
- The sample above is from a York, PA, analysis, and seems to be missing some roads. I opened the exported neighborhood_ways shapefile in QGIS and confirmed that they're not there.
Rebuild the `tilemaker` container and run it.  You can create a job locally and run the analysis then the tilemaker commands that get printed to the logs, or you could run tile generation for an already-finished analysis, along the lines of …
=> Offset segments to show both directions in neighborhood_ways tiles

src/django/pfb_network_connectivity/settings.py
If a job isn't taken within an hour, boundary downloads on the
analysis container fail because the S3 signed url expired.
Bumps default expires timeout to two weeks to address this.
Was unable to test as configured, but tested the opposite case:
- Set `AWS_QUERYSTRING_EXPIRE = 1`
- Open up django shell and do: `Neighborhood.objects.first().boundary_file.url` and copy the url
- Navigate to url in browser, should get permission denied error
Closes #270
=> Sign Neighborhood boundary files for two weeks by default

deployment/README.md, deployment/terraform/iam.tf, scripts/infra
Provides the necessary updates to end up with a successful production environment on AWS.
Commit https://github.com/azavea/pfb-network-connectivity/commit/d32e6a5ebe056702ed119e220a473f6fdd840cfd is live on the production stack.
Got error:
```
* aws_ecs_service.pfb_app_http: InvalidParameterException: The target group with targetGroupArn arn:aws:elasticloadbalancing:us-east-1:950872791630:targetg$
oup/tf-tg-6defea6dd9c9c22ca88749d107/54fbe71805823763 does not have an associated load balancer.
status code: 400, request id: 32e019c6-2041-11e7-9b66-c5845ed8449f "ProductionHTTPAppServer"
```
while launching stack but I believe that was fallout from the previous error where the IAM Role BatchManageJobs failed to create because it already existed. After fixing the IAM role error, deleting the …
=> Production deployment

src/django/pfb_analysis/filters.py
Filter AnalysisJob API endpint by neighborhood name (slug) or label, either as exact match or substring.
Closes #243.
Here's some relevant [django filter docs](https://django-filter.readthedocs.io/en/latest/ref/filters.html#).
* Create one or more analysis jobs
* Should be able to query analysis jobs by neighborhood name (slug) or label
* Should be able to query for exact match
* Should be able to query for substring using `__contains` syntax, like: http://localhost:9200/api/analysis_jobs/?neighborhood__label__contains=somestring
=> Add filters for analysis job by neighborhood name

deployment/ansible/group_vars/all.example, deployment/ansible/roles.yml, deployment/terraform/batch-container-service.tf, deployment/terraform/config.tf, deployment/terraform/iam.tf
Currently, the AWS Batch Container instances are using the `ecsStagingInstanceProfile`, which has permissions that unnecessary for Batch, including full Cloudwatch Logs access and SES access. This PR adds a separate Batch container instance profile to ensure that each service has the minimum amount of access that is necessary.
Additionally, this PR updates `deployment/ansible/group_vars/all.example` with values necessary for provisioning.
The `BatchInstanceProfile` includes the permissions indicated in the [AWS Docs](http://docs.aws.amazon.com/batch/latest/userguide/instance_IAM_role.html), and also adds S3 access so that analysis jobs can store their results. 
* Provision the VM
* run `GIT_COMMIT=682b1e1 scripts/infra plan` according to …
=> Create and associate new IAM instance profile with batch container instances

src/analysis/connectivity/access_overall.sql, src/analysis/connectivity/census_blocks.sql, src/analysis/connectivity/overall_scores.sql, src/analysis/connectivity/score_inputs.sql, src/analysis/scripts/run_connectivity.sh, src/django/pfb_analysis/fixtures/analysis-score-metadata.json
Adds new field "overall_score" to neighborhood_census_blocks. This is the field we can use to generate tiles for viewing census block scores.
=> Overall scores in census blocks

src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.html, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py
Switches the analysis-jobs endpoint from including UUID and label as properties on the job to including `neighborhood` as an object, with those details plus state and point geometry inside.
Since DRF doesn't have easy automatic behavior for saving inlined related objects, I borrowed an idea from MUB and made neighborhood on the AnalysisJob serializer into a field that expects UUID for create/save operations but includes the serialized object when serializing for presentation.
Example result:
```
{
"uuid": "acc421de-2832-4252-87e0-5f1c828452bb",
"createdAt": "2017-04-07T01:12:12.827062Z",
"modifiedAt": "2017-04-07T04:09:36.021285Z",
"running_time": 11461,
"start_time": "2017-04-07T01:16:32.001600Z",
"status": "COMPLETE",
"neighborhood": {
"uuid": "08f827a6-c21a-4e45-959e-42cc509bb6fc", …
```
=> Include neighborhood object in job api results

src/django/pfb_analysis/serializers.py
Adds a link to the AWS logs for the job, making it easier to inspect failed jobs.
Again, not pretty, but its selectable and copy/pastable into a browser.
* Create job via UI, ensure url exists once job is started
Closes #296
=> Add job logs url to AnalysisJob detail view in admin

src/analysis/connectivity/overall_scores.sql, src/django/pfb_analysis/fixtures/analysis-score-metadata.json
Adds two new entries to neighborhood_overall_scores. One is the total population of the boundary area (summary of pop10 attribute in census blocks). The second is a categorization of the city:
- 1=large
- 2=medium
- 3=small
Current breaks are set at >= 500,000 (large city) and >= 100,000 (medium city).
The score_id is `population_total` for the population and `population_category` for the category.
1. Run analysis
2. Check for new scores
=> Add boundary population category to neighborhood_overall_scores

src/analysis/scripts/entrypoint.sh, src/tilemaker/entrypoint.sh, src/tilemaker/scripts/run_tilemaker.sh
Properly catches and returns exit code of the main script in the entrypoint scripts. This allows Batch to properly detect exit codes and kill downstream jobs in the DAG
Using the `set +e ... set -e` strategy seemed like the most clean way to go about this. If `-e` is left set, then there is no way to DRY the error handling as the script immediately exits without getting a chance to save the error code as demonstrated by this sample script (play with adding/deleting the `set -e` line):
```bash
#!/bin/bash
set -e
function fail() {
return 1
}
fail
ERR=$?
if [ $ERR -eq 0 ]; then
echo "Success: $ERR"
else
echo "Failure: $ERR"
fi
```
Then again my bash-fu is pretty mediocre and I might have missed a better way (TM).
* Not really possible to test locally, but this branch is deployed on staging …
=> Better error handling for both batch jobs

src/analysis/scripts/export_connectivity.sh
Protects against empty geometry, which makes `ogr2ogr`, and hence the export script, crash.
A little hard to pick out between the "More than one geometry column" warnings, but here's the command that gets run by `export_connectivity.sh` failing then succeeding in its "before" and "after" forms.
- I looked into downloading the `pgdata` for jobs off the batch worker.
Per [this answer](https://unix.stackexchange.com/a/327100) referencing [this line of the `scp` code](https://github.com/openssh/libopenssh/blob/master/ssh/scp.c#L375), scp doesn't support agent forwarding.  The strategy I did get working ([from here](https://serverfault.com/a/37664)) was opening one connection to the bastion that forwards the ssh port on the batch instance to another port, which you can then use to establish …
=> Don't try to export features with empty geometry

src/angularjs/.eslintrc, src/angularjs/bower.json, src/angularjs/src/app/components/map/map.directive.js, src/angularjs/src/app/components/map/module.js, src/angularjs/src/app/components/module.js, src/angularjs/src/app/home/home.controller.js, src/angularjs/src/app/home/home.html, src/angularjs/src/app/home/module.js, src/angularjs/src/app/index.module.js, src/angularjs/src/app/index.route.js, src/angularjs/src/styles/components/_map.scss
This is part 1 of a two part set to add the neighborhoods map at the bottom of the public homepage. I stopped here since this PR adds a HomeController and adds the MapDirective that can be used elsewhere. I will continue work on displaying the neighborhoods on the map in a separate branch/PR.
Kept the map directive as simple as possible. Added options to set map options/bounds/zoom/center/baselayer but anything else needs to be dealt with using the pfbMapReady function which provides the map object to the wrapping controller. This MapDirective should be sufficient for the individual static maps in the cards all over the site as well as for the larger more interactive maps.
@designmatty should we use a default basemap other than Stamen toner lite?
* Load up page, see map
Connects #247
=> Reusable map component with basic configuration

src/django/pfb_analysis/management/commands/analysis_batch_create.py
Looks for attribute 'osm_url' on each shapefile feature
Updates command added in #178 to set `AnalysisJob.osm_extract_url` if attribute `osm_url` is available in the shapefile (shorter due to DBF 10-char limit on column names).
Shapefile:
Trigger Batch:
Job has Batch ID and OSM extract url set:
We will need to take the shapefile provided to us and fill in the osm_url column in that shapefile with appropriate urls for each of the larger boundaries (basically any that falls within a MapZen metro extract)
Run:
```
./scripts/django-manage analysis_batch_create --submit https://s3.amazonaws.com/pfb-batch-run-inputs-us-east-1/testing/pfb_city_boundaries_with_osm.zip
```
Inspect "CREATED" jobs in admin UI, `York` and `Allentown` should have `osm_extract_url` set, and `Lancaster` should not. …
=> Set osm_extract_url in batch management command if available

src/angularjs/src/app/components/neighborhoods.service.js, src/angularjs/src/app/home/home.controller.js, src/angularjs/src/app/home/home.html, src/angularjs/src/app/home/module.js, src/angularjs/src/app/home/neighborhood-map.directive.js, src/angularjs/src/app/home/neighborhood-map.html
Part 2 after #316. Adds the neighborhoods as geojson points to the map.
- Not styled
- Link to neighborhood detail view not hooked up. Can be done as part of #254 
@designmatty we'll need to think about how we want to style the markers/popups in this view
I intentionally left the map bounds set to CONUS because the final application will have points across the US.
Refactors the neighborhood map logic into a self-contained directive
Closes #247
=> Load Neighborhood geojson on map

src/angularjs/src/app/index.route.js, src/angularjs/src/app/places/detail/module.js, src/angularjs/src/app/places/detail/places-detail.controller.js, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js, src/angularjs/src/app/places/module.js
Add places detail view and implement sorting and filtering for places list.
Closes #250 and closes #254.
Neighborhood name dropdown filter:
A detail view:
Detail view when there's no scores to see:
Did not attempt to implement download dropdown. Not sure what should go in there; there's _a lot_ of links available in the response, at various nesting levels.
* Go to http://localhost:9301/#/places/
* Try filtering by neighborhood name: should be able to type stuff for autocomplete, or click things
* Try changing sort order (note #322 may make for some odd-looking score sort results)
* Click a neighborhood in the results list to go to details page; should have scores listed
* Clicking a neighborhood without a valid completed job shows a message about 'no results available'
Closes #250 
Closes …
=> Feature/kak/places detail#254

src/analysis/import/clip_osm.sql, src/analysis/import/import_osm.sh
Clips OSM extract by the extent of the trimmed census blocks which is equal to the extent of the boundary + buffer. In the default case, buffer == max_trip_distance. This leads to only slightly more OSM data than is necessary, which was not necessarily the case in the old extent calculation. It also allows us to reduce the amount of data we're pulling from the Overpass API.
OSM extent for a local Germantown job using the MapZen Philadelphia OSM extract:
`osmconvert` allows clipping via a `.poly` file, which is an arcane format which would have required extensive processing to create using the union of the clipped census blocks, and would only be slightly better in the 'average' case. In the best case, where the boundary+buffer is almost square, the extent would be almost equal to using a …
=> Clip OSM extract by census block extent

src/angularjs/src/app/home/home.controller.js, src/angularjs/src/app/home/home.html
Display information on top eight scoring cities on homepage.
Closes #245.
* Visit home page at http://localhost:9301/#/
* Should have list of cities under "Leading Cities/Towns" header, if there are any completed jobs
* Should be ordered top-scoring first, and only show top eight
* Clicking a city card should go to the places detail page for that neighborhood
Connects #245
=> Implement city cards on homepage

deployment/ansible/group_vars/all.example, deployment/terraform/config.tf, deployment/terraform/iam.tf
Bump terraform version to 0.9.3, which removes the `lock` configuration parameter and uses `role` instead of `roles` in the `aws_iam_instance_profile` resource.
n/a
Terraform also adds the `treat_missing_data` option to work with a new [CloudWatch feature](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data). The default of `missing` seemed appropriate so I left it as is.
* Ensure that you can run `scripts/infra plan` according to the directions in the `README`
=> Bump terraform version to 0.9.3

scripts/infra
After a long series of exhaustive tests, it was found that a subset of SHA1 hashes were being parsed nondeterministicly. In order to always interpret SHA1 hashes as strings, quote the value of `git_commit`.
Fixes https://github.com/azavea/pfb-network-connectivity/issues/340
I created a small Terraform project with the following configuration:
```hcl
variable "git_commit" {}
output "git_commit" {
value = "${var.git_commit}"
}
```
Using that, I crafted the following test using Bats:
```bash
#!/usr/bin/env bats
@test "terraform SHA variable handling" {
sha="$(echo $RANDOM | shasum | cut -c1-7)"
echo "SHA = ${sha}"
rm -rf test.tfplan
./terraform plan -no-color -var="git_commit=${sha}" -out test.tfplan > /dev/null
run ./terraform apply -no-color test.tfplan
[ "${lines[2]}" = "git_commit = …
```
=> Quote passing of Git commit SHA to Terraform

src/angularjs/src/app/places/list/places-list.controller.js, src/django/pfb_analysis/filters.py, src/django/pfb_analysis/views.py
When sorting public places view alphabetically, sort by state first, then label.
Closes #327.
The DRF `ordering` parameter apparently [accepts a comma-separated list](https://github.com/encode/django-rest-framework/blob/33290170e875b3c48782224910cc07c278e395bb/rest_framework/filters.py#L201) of fields to order by, so this simply adds `state_abbrev` as an available field to use in ordering, then modifies the front end to sort by that first.
* query http://localhost:9200/api/analysis_jobs/?ordering=neighborhood__state_abbrev,neighborhood__label
* Should get jobs ordered by neighborhood state, then label
Connects #327
=> Sort places by state, then label

src/angularjs/src/app/components/module.js, src/angularjs/src/app/components/thumbnail-map/module.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.directive.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.html, src/angularjs/src/app/home/home.html, src/angularjs/src/app/home/neighborhood-map.html, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/styles/components/_card.scss, src/angularjs/src/styles/pages/_mapping.scss
Adds a directive for loading thumbnail static maps, as used in places cards on public home view and places list.
In places list:
On home page:
Does not load the neighborhood results/centroid layer. Should be straightforward to add in `onMapReady` when available.
* First card on homepage should have map http://localhost:9301/#/
* Exisitng neighborhood map on homepage should still display correctly
* Places in list at http://localhost:9301/#/places/ should have map on left
Connects #337
=> Feature/kak/thumbnail maps#337

deployment/terraform/iam.tf, deployment/terraform/storage.tf
Makes the results bucket public and adds CORS permissions so that the feature geojson files and the tile layers can be accessed by the front-end.
Even without of setting up CloudFront we might be able to get more fine-grained with the permissions policy, but for now this does the job.
I applied this to the staging site, so any file in the `staging-pfb-storage-us-east-1` bucket should now be accessible at the key path appended to https://s3.amazonaws.com/staging-pfb-storage-us-east-1/.
The static tile layer URLs would be `https://s3.amazonaws.com/staging-pfb-storage-us-east-1/results/<JOB_ID>/tiles/<LAYER_NAME>/{z}/{x}/{y}.png`, where `LAYER_NAME` is "neighborhood_ways" or "neighborhood_census_blocks".
Resolves #353, resolves #350.
=> Make results bucket public

src/angularjs/bower.json, src/angularjs/src/app/components/filters/analysis-job-filter.directive.js, src/angularjs/src/app/components/filters/analysis-job-filter.html, src/angularjs/src/app/components/filters/module.js, src/angularjs/src/app/components/filters/user-filter.directive.js, src/angularjs/src/app/components/filters/user-filter.html, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js
Banish `ui.select` control from Angular app. Use Bootstrap typeahead instead. The select control offers a scrolling dropdown that can grow quite large; the typeahead control gets limited to the first eight matches by default.
Also modified neighborhood filter control to include the state in the autocomplete label:
Note #305 is still outstanding (admin styling is broken).
* Rebuild angular container
* Try out filters for admin analysis jobs: http://localhost:9301/#/admin/analysis-jobs/
* Also for user management: http://localhost:9301/#/admin/users/
* Also also for public 'places' list: http://localhost:9301/#/places/
Closes #328
Incidentally closes #329 (by removing the control)
=> Feature/kak/typeahead search#328

src/angularjs/src/app/components/map/map.directive.js, src/angularjs/src/app/places/detail/places-detail.controller.js, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/map/module.js, src/angularjs/src/app/places/map/places-map.directive.js, src/angularjs/src/app/places/map/places-map.html, src/angularjs/src/app/places/module.js
Adds map to public places detail view with a control containing the results GeoJSON layers.
A popup:
Things not done:
- Display neighborhood bounds polygon, as there is currently no endpoint for that (will we add one?)
- Properly zoom/fit map to neighborhood area. If we add bounds polygon, can be accomplished with that
- Style results markers/popups. At the least, should vary marker color by layer to distinguish
- Display results tile layer (depends on #350).
At least for my test run for Philly, many of the results were missing values for low/high stress and pop. score; there were some for some schools in the 'university' layer (as in popup pictured above).
* As a workaround for #349, go to your S3 results bucket and enable CORS
* Visit places detail page
* Should get a map with a layer …
=> Feature/place detail map#255

src/django/pfb_analysis/models.py
We add a status update to set QUEUED when we submit a job, so
calculating running time from the first status update of any kind means
including all the time spent waiting to start.  IMPORTING is the first
status set by the actual analysis, so start from there instead.
It's hard to see the difference in development, because we don't set the QUEUED status there. But you could set it manually to see the difference.  Or just confirm that `running_time` still returns sensible answers.
=> Calculate running_time from first IMPORTING status

deployment/aws-batch/job-definitions/production-pfb-analysis-run-job.json, deployment/aws-batch/job-definitions/production-pfb-tilemaker-run-job.json, deployment/aws-batch/job-definitions/staging-pfb-analysis-run-job.json, deployment/aws-batch/job-definitions/staging-pfb-tilemaker-run-job.json
AWS Batch added a "retryStrategy" option that allows for automatic retries in case a job returns a non-zero exit code. This provides a single automatic retry in the case of transient AWS/network issues, backing instance termination, etc. I didn't think more than one retry is necessary, but I could bump attempts to 3.
The job is not retried if cancelled or manually terminated.
Any progress is lost and jobs are restarted from the beginning.
Nothing really, I'm going run a few tests after this is merged and deployed and submit a followup PR if necessary to address any issues.
=> Attempt a single retry in case of job failure

README.md, src/django/pfb_analysis/models.py, src/django/pfb_network_connectivity/settings.py
A bit more fallout from running batches. In this case, it appears pre-singed URLs are failing if they sit in the AWS Batch queue for too long. The presigned url is set to expire after two weeks, but since the requests are generated on an EC2 instance, they contain an `x-amz-security-token` which contains the EC2 instance temporary credential used to sign the request, and this fails, presumably because the EC2 credentials are rotated by the time the signed url is used. In any case, in #354 we made the storage bucket public so this just switches to use unsigned urls for all objects that live in the storages bucket.
@KlaasH you might want to take a look as well, since this requires running a command to update your dev storage bucket permissions.
If you don't already have your local storage …
=> Cleanup Django S3 url signing

src/angularjs/src/app/components/map/map.constants.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.directive.js, src/angularjs/src/app/home/neighborhood-map.directive.js, src/angularjs/src/app/home/neighborhood-map.html, src/angularjs/src/app/places/detail/module.js, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/app/places/detail/place-map.html, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/list/module.js, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list-map-directive.js, src/angularjs/src/app/places/list/places-list-map.html, src/angularjs/src/app/places/map/module.js, src/angularjs/src/app/places/module.js, src/django/pfb_analysis/serializers.py
Implement map view on public places list page and load layer with neighborhood points. Also added a map constants file for shared use by the map directives in setting up base layers. Moved existing places detail map under `detail` module, as it can't be readily shared with the list page map.
With satellite layer selected:
Also fixed an issue where the new `geom_simple` GeoJSON was loading in the default neighborhood API endpoint (that endpoint should have no geometries in it).
#251 should add overlay centered over map for a places comparison overview.
* Visit places page at http://localhost:9301/?#/places/
* Should get points layer of places, like on home page
* Should have a layer switcher with a secondary satellite base layer option
Closes #249
=> Feature/kak/places list map#249

deployment/aws-batch/job-definitions/production-pfb-analysis-run-job.json, deployment/aws-batch/job-definitions/production-pfb-tilemaker-run-job.json, deployment/aws-batch/job-definitions/staging-pfb-tilemaker-run-job.json, src/tilemaker/Dockerfile, src/tilemaker/entrypoint.sh, src/tilemaker/scripts/run_tilemaker.sh, src/tilemaker/scripts/split_bbox.py
Makes tilemaker much more parallel, using GNU `parallel`.
In addition to running one command per zoomlevel, it also divides the bounding box into segments and runs one command per segment.  The default I went with is 4.  Any tile that falls at all within a boundary gets generated, so more partitions would result in more tiles getting generated twice.  So I only used the partitioning at higher zoomlevels (cutoff of 13 chosen somewhat arbitrarily).
I also increased the resources limits in the job definition, since it should be able to make use of them now.
I didn't split ways and blocks into separate tasks.  It would be pretty easy to do so, but a little attention would have to be paid to how to keep the first one that finishes from updating the status to COMPLETE prematurely.
I'm out for …
=> Parallelize tilemaker

src/angularjs/src/app/components/neighborhoods.service.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.directive.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.html, src/angularjs/src/app/home/home.html, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/app/places/detail/place-map.html, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/list/place-list.html
Load neighborhood bounds on the thumbnail maps in home page top places cards and in places list, as in the prototype.
In list:
On homepage:
Might hold off on merging this until #368 is in, to rebase for the constants refactor.
* Check for proper bounds display/zoom/fit
* In list cards: http://localhost:9301/?#/places/
* And on home page
Closes #357
=> Load neighborhood boundaries on thumbnail maps

src/angularjs/gulp/build.js, src/angularjs/gulp/conf.js
Apparently Leaflet does not properly include image assets in its bower configuration for the bower gulp plugin to pick up, so explicitly include them when gathering image assets.
Leaflet expects its images to be in a different location (`/styles/images/`) than where our other images are stored (`/assets/images/`). So, broke this out into a separate task from the app image gulp task.
Inside VM:
* rebuild assets for production: `docker-compose build angularjs`
* restart containers: `./scripts/server`
* log into frontend container: `./scripts/console angularjs -it /bin/bash`
* check out images: `cd dist/styles/images/`
Should have leaflet images in directory, including `layers.png`. Path should match what staging/prod servers are expecting, which is a relative path like …
=> Add Leaflet images to dist build

src/angularjs/src/app/components/thumbnail-map/thumbnail-map.directive.js, src/angularjs/src/app/index.route.js, src/angularjs/src/app/places/compare/compare.controller.js, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js, src/angularjs/src/styles/pages/_mapping.scss
Implement comparison feature on places list page.
Dropdown list items are currently unstyled.
Also added a footer to the comparison page cards to link to the place detail, since that was in the wireframes.
Refactored some of the comparison place tracking to preserve the offsets of selections, so the cards don't shift around on going back and forth between the place list and comparison pages after removing a selection.
* Go to [places list](http://localhost:9301/#/places////)
* Should be able to add and remove places for comparison
* Shouldn't be able to add the same place twice
* Should be able to get to comparison page with current selections using last option in compare drop-down
* Should be able to move between compare and list page with selections preserved
Closes #251
=> Feature/kak/places list compare#251

src/angularjs/src/app/components/navbar/navbar.html
In navbar for public site, add link to feedback page.
Closes #351.
* Link should appear on public site navbar and not in admin site navbar
* Should open feedback page in new tab
Closes #351
=> Add feedback link

src/angularjs/src/app/components/footer/footer.directive.js, src/angularjs/src/app/components/footer/footer.html
For access to admin site login from public site.
Supersedes #391. Since the public site doesn't function yet without logged-in API access, attempting to view home page when logged out will still simply redirect to login (Only 'sign out' link can be seen in footer currently.)
* Should be able to log out via 'Sign out' link in public page footer; should redirect to login page
Closes #312
=> Add log in/out links to footer

src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py, src/django/pfb_network_connectivity/urls.py, src/django/requirements.txt
To address API performance issues reported in #373, directly serialize GeoJSON responses in database. Removes Djangonauts serializer.
Public UI front page json load times before:
Public UI front page json load times after:
These are for a database with only five neighborhoods loaded. For a larger set, the improvements should be considerably greater.
Single [query for raw GeoJSON of neighborhood points](http://localhost:9200/api/neighborhoods/?format=json), before:
After:
Intend to leave #373 open until deployed to production, where performance effect can be better evaluated.
Also bumped minor/bugfix versions of the Django dependencies.
When permissions modified on neighborhoods in #387, these queries will need to modifed to filter appropriately.
* Rebuild Django container
* Should get …
=> Feature/kak/direct geojson serialization#373

src/angularjs/src/app/components/footer/footer.html, src/angularjs/src/app/components/navbar/navbar.html, src/angularjs/src/app/home/home.html, src/angularjs/src/app/home/neighborhood-map.html, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/list/place-list.html
Replace occurrences of 'city/town' or 'location' with 'place'.
Also remove spaces from 'People for Bikes' in header and footer.
Addresses items 1-4 in the [document](https://docs.google.com/a/azavea.com/document/d/1NNj8k7D8ySqROuCA2QQkWZfb4HB9zxjzVlsDISr4P6E/edit?usp=sharing) linked to on #380.
Searched for occurrences of 'city' or 'town' in the angular app and replaced all user-facing occurrences with 'place'.
The document calls for taking the spaces out of 'People for Bikes' in the header, replacing with camel case. While that looks fine in the footer, the header does an uppercase text transform, so the camel casing is lost. Tried excluding the uppercase transform from just that link text, but it looked odd next to the others. Here's how it is now:
Maybe @designmatty knows of a better …
=> Text changes to UI to use 'place'

src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/filters.py, src/django/pfb_network_connectivity/permissions.py
Allow read-only access to neighborhoods and analysis jobs, to support use of the public site without login. 
* Log out of UI and API
* Should be able to get results from http://localhost:9200/api/neighborhoods/
* Should be able to get results from http://localhost:9200/api/analysis_jobs/
* Should not be able to perform POST operations on those endpoints
* Should not be able to access other, protected endpoints, i.e. http://localhost:9200/api/organizations/
Closes #382.
=> Allow read-only access to neighborhoods and analysis jobs

src/django/pfb_analysis/views.py
Allow unauthenticated requests to API endpoints used by public site.
Fixes up changes in #398 that overlapped changes in #394. Makes read-only GeoJSON endpoints publicly accessible.
* Public UI should work when logged out
Closes #388
=> Allow unauthenticated requests

src/django/pfb_analysis/views.py
Restores lost ability to create AnalysisJob/Neighborhood objects as an admin user. 
Permissions are implemented via custom Permission classes,
and do not interface with the Django model permissions feature.
So IsAuthenticatedOrReadOnly is sufficient here.
Ensure a public user can still access GET for analysisjob, neighborhood and the geojson endpoints.
Ensure a logged in viewer user can view the same GET endpoints, but no user/org info or write to analysisjob/neighborhood
Ensure an admin user can write to everything.
Connects #402
=> Fixup admin users unable to create AnalysisJob/Neighborhood

src/analysis/connectivity/census_block_jobs.sql, src/analysis/import/import_jobs.sh
Adds some logic to attempt downloading 2013 jobs data if wget encounters an error response. I didn't see a way to safely and consistently better scope the condition to only a 404 error.
List of wget error codes: https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
Download the [Casper, WY shapefile](https://s3.amazonaws.com/production-pfb-storage-us-east-1/neighborhood_boundaries/casper-wy/casper-wy.zip) and create a new neighborhood in development. Then trigger a local job after creating one for this boundary via the admin UI. Let it run through the jobs import and ensure that the 2013 data is subbed for the 2014 data. Consider killing the job after this point as it will take a long time to run to completion.
Additionally, run a simple Germantown, Phila job afterwards to …
=> Fallback to 2013 jobs data if 2014 can't be pulled

src/analysis/connectivity/overall_scores.sql, src/analysis/connectivity/score_inputs.sql
This addresses https://github.com/azavea/pfb-network-connectivity/issues/370 by adding a check for conditions that would result in a zero in the denominator in the overall scores.
**Please note**: I have not tested this but wanted to push this out quickly so you can keep moving on scores. I can test next week if you don't have an opportunity to get to it before I do.
* Run scores for area with known division by zero
* Check for div/zero errors
* Run scores for area that ran successfully
* Check score results to make sure they match
=> Add check for zero in denominator on neighborhood_overall_scores.sql

src/angularjs/src/app/components/places.service.js, src/angularjs/src/app/components/scoremetadata.service.js, src/angularjs/src/app/places/detail/places-detail.controller.js, src/angularjs/src/app/places/detail/places-detail.html, src/django/pfb_analysis/fixtures/analysis-score-metadata.json, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/urls.py
Adds score labels and descriptions to the places detail view
The description tooltips won't currently display because the fontello.css file isn't being built into the application bundle. I spent 15 mins attempting to fix it but no luck, needs a bit more digging to get properly bundled. The description text is added to the DOM, so if you manually give the tooltip div a width via dev tools you can hover the blank div and view the tooltips.
- `./scripts/django-manage loaddata analysis-score-metadata`
- Navigate to places detail page
- Labels should replace the score names, and descriptions should exist in the DOM 
- http://localhost:9200/api/score_metadata/ should exist and return data without logging in
Closes #378
=> Add score labels/descriptions to public UI

README.md
Fixes README error found while @designmatty was provisioning his VM
=> Fix group_vars cp command in README

src/angularjs/src/app/components/scoremetadata.service.js, src/angularjs/src/app/components/states.service.js, src/angularjs/src/app/places/compare/compare.controller.js, src/angularjs/src/app/places/compare/compare.html
Add score labels from new metadata endpoint to comparison page metrics.
* Check compare page
* Metrics should have pretty labels and still line up across columns
Closes #428.
=> Display scores using metadata on compare page

src/angularjs/bower.json, src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.html, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/app/places/detail/places-detail.controller.js, src/django/pfb_analysis/models.py, src/django/pfb_analysis/views.py
Makes two main changes to the place detail map:
- Adds the generated tile layers ("ways" and "census blocks")
- Makes the destination layers "pick one" (radio) rather than checkboxes
This is using the [leaflet-groupedlayercontrol](https://github.com/ismyrnow/leaflet-groupedlayercontrol) plugin.  That gets us the ability to make groups mutually exclusive.  The thing it doesn't have that the regular `L.Control.layers` does is sorting.  The regular picker supports two groups (base maps and overlays), so it's possible to get the separation we want by putting our overlays in as the base maps and our destinations in as overlays.  But we can't get the destinations to be radio buttons.  Probably that's more important than sorting, and we could possibly get them to sort by some other means if we …
=> Add tiles and make layers exclusive on detail map

src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list-map-directive.js, src/angularjs/src/app/places/list/places-list.controller.js
Makes the map reappear and implements the additional functionality detailed in #418:
Missing map was due to an improperly matched div in the `div.sidebar-header`
Implements the geojson map filtering in such a way that it would be relatively trivial to add the functionality detailed in #431 
Navigate to places list, see map. Do some filtering, choose some to compare, compare items should always show, map should update on list filter and compare selection changes.
To test #415, make the vertical height of your window small enough that scrolling should activate, then scroll.
Closes #415, Closes #418
=> Feature/awf/angular fix list map#418

src/django/pfb_analysis/filters.py
Filter job search on neighborhood label instead of name
**Before:**
**After:**
- Enter search queries that match the names presented in the UI. Search should filter as expected.
Closes #440
=> Filter job search on neighborhood label

src/angularjs/src/app/home/home.html, src/angularjs/src/styles/pages/_home.scss
This will remove the placeholder image section from each score card on the homepage. It adds the stripe of red/blue/white at the top of each card to give a little life to each card.
Connects #411
=> removes image section from score cards

src/angularjs/src/app/leaflet/map-button.control.js, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/styles/components/_map.scss
Adds the print button on the map as expected in the wireframes via an almost trivially simple `MapButton` leaflet control.
Then click button:
Print view is unstyled, will require additional design work.
Currently uses the `leaflet-control-layers` class to match the styling of the other controls. That seemed reasonable for now.
Click tiny button, see print view.
Closes #396
=> Add print button to place detail map

src/angularjs/src/app/home/home.controller.js, src/angularjs/src/app/home/home.html, src/angularjs/src/app/methodology.html, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js, src/django/pfb_analysis/fixtures/analysis-score-metadata.json
The one remaining issue for #464 is the tooltip text for "BNA Score" at the top of the detail page. This comments it out, since we don't have the desired text yet.
The change to the score descriptions ("how people score on access to X" tooltips -> "how well people can reach X by bike") applied pretty smoothly.  The one that I didn't change was "On average, this is how people score for overall access."  It doesn't quite fit the pattern and I couldn't readily think of a way to adapt it to be closer.
- run `./scripts/django-manage loaddata analysis-score-metadata`, since this changes the analysis score metadata
- go on a scavenger hunt for the things listed in https://docs.google.com/a/azavea.com/document/d/17DwS_olu8S1kcMGDKGEaRwLJ8wXBvRaHGXj0A5aeZe8/edit?usp=sharing
Connects #464.
=> Apply text fixes and changes per feedback

src/angularjs/src/app/places/list/place-list.html
The current compare button has functionality that is a bit unusual. This will update to reflect expected behavior
Connects #441
=> updates compare button to expected functionality

src/angularjs/src/app/components/places.service.js, src/angularjs/src/app/places/list/places-list.controller.js, src/django/pfb_analysis/models.py, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py
Adds "Population" to the "Sort By" options on the Places list view.
- I used the same method we used for `overall_score`, pulling the value out of the jsonb field into a pseudo-property of the AnalysisJob using an annotation.
- There's no `score_normalized` on the `population_total` metric, so this includes a workaround to use `score_original` for that specific one, which fixes the bug whereby it has been always showing zero.
Select "Population" and watch it resort accordingly.  Of course this assumes you have multiple completed jobs and that their populations are such that you can tell one sort order from another...
Resolves #395.
=> Option to sort places by population

src/angularjs/src/app/places/detail/place-map.directive.js, src/django/pfb_analysis/models.py
- #459: Renames the tile overlay layers
- #460: Changes the default overlay to "Stress Network" (formerly "ways")
- Capitalizes feature layers (just seemed sensible/more consistent)
I just did everything right in `place-map-directive.js`.  There was already a fair bit of hard-coded formatting going on in there, and there's no obvious place for the config to go if we wanted to separate it out from the logic.  So rather than pull what's there out, I decided to just add this to the pile.
Only affects the place details page.  It should show the network layer on load and look like the screenshot.
Resolves #459, resolves #460.
=> Set layer names and show "Stress Network" by default

src/angularjs/src/app/methodology.html, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/styles/components/_map.scss, src/angularjs/src/styles/components/_tooltip.scss, src/angularjs/src/styles/pages/_location.scss
- Cleans up Place page, including sidebar list, print button (not print css) and download dropdown
- Removes image markup from methodology page
- Change tooltip's functionality from using `title` to `data-title`. This was done to prevent the browser's default title hover from showing over the app's tooltip hover interaction.
* Hover tooltips
* Try downloading from dropdown
- fixes #463
- fixes #462
=> clean up places and methodology page

src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.html, src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.html, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/help/help.html, src/angularjs/src/app/login/login.html, src/angularjs/src/app/neighborhoods/create/neighborhoods-create.html, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.html, src/angularjs/src/app/organizations/detail/organizations-detail.html, src/angularjs/src/app/organizations/list/organizations-list.html, src/angularjs/src/app/password-reset/request/password-reset-request.html, src/angularjs/src/app/password-reset/reset/password-reset.html, src/angularjs/src/app/users/detail/users-detail.html, src/angularjs/src/app/users/list/users-list.html, src/angularjs/src/styles/components/_form.scss, src/angularjs/src/styles/components/_panel.scss, src/angularjs/src/styles/components/_table.scss, src/angularjs/src/styles/index.scss
This PR attempts to cleanup all admin pages including auth pages, user management, etc.
Tables and panel styling have been added to the scss.
Removes all reference to bootstrap grid system since we aren't using it.
* View login and password reset pages
* View all admin pages
Connects #305
=> cleans up all admin facing pages

src/angularjs/src/app/components/footer/footer.html, src/angularjs/src/app/components/navbar/navbar.html, src/angularjs/src/styles/layout/_navbar.scss
This PR will remove the about link from the navbar and the footer. There are also active states for the links in the navbar.
Fixes #450
=> removes about, adds active states to navbar

src/angularjs/src/app/home/home.controller.js
Fixes bad encoding on home page score cards. HTML encoding doesn't work, presumably due to angular's internal escaping.
Trivial, merging.
=> Fix bad escape in people score calc on about page

src/angularjs/src/app/components/map/map.constants.js
Add a link to OSM informational page from map attribution for the OSM-based base layer options (but not the satellite map.) Displays on all non-thumbnail maps, as the thumbnail maps do not display the attribution.
Closes #485.
=> Add map attribution link to OSM

src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js
Implements section headers in place list view for the alphabetical and population sort options.
Section headers are sorted alphabetically before rendering, which works for the two options we're using for now ('Large', 'Medium', 'Small', 'Unknown' sorts in the proper order). Would need to implement an additional option if we needed to sort the headers in some other way.
The lodash groupBy documentation states that 'the order of grouped values is determined by the order they occur in collection, so original sort order within a section is preserved through the groupBy for when we later render each place.
Use of a special key for not displaying a section header is a bit janky, but wasn't sure of a better way to allow for some sort options to show headers and some to not do so without …
=> Implement section headers for alphabetical/pop sorting

src/angularjs/src/app/components/scoremetadata.service.js, src/angularjs/src/app/places/compare/compare.controller.js, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/styles/components/_metrics.scss
Modify display of scores lists on comparison page and places detail page:
- sort metrics into category
- alphabetize by category
- list 'total' score for category, if it exists, first
- if 'total' exists, indent other metrics (sub-scores) listed below it
Top of places detail:
Bottom of comparison page list:
One category is an empty string, and so sorts first (population and the 'people' score.)
Identifying the category total metric relies on finding 'Total', preceded by a space, in the metric label; the space is required because one of the metrics is called 'Total Population', which does not represent a summary metric for its category.
Closes #457
=> Feature/kak/indent subscores#457

src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/styles/components/_button.scss, src/angularjs/src/styles/pages/_location.scss
Add button to header of place detail page that links to compare page.
Current place gets put in first slot of comparison page.
@designmatty might want to look at this. Default button styling is grey text until hover, which looks somewhat low-contrast on the grey header bar.
Closes #489.
=> Add detail compare button

src/angularjs/src/app/places/compare/compare.html
On comparison page, display N/A for missing results instead of hiding the list item.
Lines up results visually, and also fixes issue with relative map heights differing.
List element for missing scores would be hidden, causing results to not line up and map to appear taller (here, 'Trails' is missing from the score list on the right):
* Log in to django console and delete a score result for a completed analysis
* Requires first saving result object, deleting key, then saving result object back (do not delete directly)
* Compare city with deleted result against one or two cities with complete results; should line up
Deleting one result at the console:
```
>>> g.overall_scores['recreation_trails']
{u'score_original': 0.0, u'score_normalized': 0.0}
>>> s = g.overall_scores …
```
=> Display N/A for missing scores

README.md
Adds a section to the README with notes for non-Windows users. I tried running on Ubuntu and noticed that an NFS daemon is required, which is not included by default.
=> Add README section with notes for non-windows users

src/django/pfb_network_connectivity/filters.py, src/django/pfb_network_connectivity/permissions.py
Do not allow `OrgAdmins` to view full admins or users outside of its org (already could not modify them).
Do not allow `OrgAdmins` to view other orgs (already could not modify them).
* Create an `OrgAdmin` user and a second organization
* Logged in as full admin, can see both organizations and all users
* Logged in as `OrgAdmin`, cannot see full admin (even if in same org) or users in other organizations
* Logged in as `OrgAdmin`, can only see own organization
Closes #408.
=> Hide more from OrgAdmins

src/angularjs/src/app/components/map/map.constants.js
Adds legend for the new Bike Infrastructure layer
For now, this is a trivial change, but it doesn't implement the white dashed line for "Track" paths. If PFB wants that styling, we'll need to address that separately.
- If you haven't already run a tile generation step to generate tiles for the bike infrastructure layer, do so.
- Toggle the bike infrastructure layer on via the neighborhood detail view
Closes #505, Connects #521
=> Add legend for Bike Infrastructure

src/analysis/features/functional_class.sql, src/analysis/import/prepare_tables.sql
Adds a column named xwalk to neighborhood_ways to identify crosswalks that should not be rendered as paths in the existing facilities layer.. A value of 1 indicates a crosswalk.
* Create a new analysis
* Check neighborhood_ways to make sure there's a column named xwalk
Necessary to complete https://github.com/azavea/pfb-network-connectivity/issues/519
=> Add flag for crosswalks

src/django/pfb_analysis/models.py
This ensures that uploaded boundary files are unique on
the same set of parameters as the Neighborhood
'unique_together' constraint.
Once merged, I'll be deleting and recreating the set of neighborhoods that exhibited this behavior on production, likely first thing Monday am. Existing neighborhoods will remain unaffected, this will only affect new neighborhoods created moving forward.
Although its likely safe in the case of UUIDField, the
Django docs state:
"In most cases, this object will not have been saved to
the database yet, so it might not yet have a value for
its primary key"
Create a new Neighborhood via the admin UI with the same name as another neighborhood, but a different state or organization. Login to S3 and note that the new neighborhood did not clobber the pre-existing …
=> Add state abbrev and organization to boundary_file path

src/angularjs/src/app/components/navbar/navbar.html, src/angularjs/src/styles/base/_print.scss, src/angularjs/src/styles/components/_metrics.scss, src/angularjs/src/styles/index.scss
Adds print styling for the place overview page.
Page breaks might happen in the middle (vertically cut in half) of a word and unfortunately there is no good way to handle those situations.
* Go to place overview page
* click on print icon
Connects #454
=> print styling

src/django/pfb_analysis/management/commands/generate_analysis_csv.py, src/django/pfb_analysis/models.py
PFBs final deliverable is a complete spreadsheet of all of the neighborhoods and the complete job ID, along with the following items:
CLI output of running command:
Spreadsheet result (only ends in .txt so that it can be uploaded here, otherwise its a csv):
[results-2017-07-26T1529.txt](https://github.com/azavea/pfb-network-connectivity/files/1177169/results-2017-07-26T1529.txt)
Area in sq miles of the approximate boundary (to test `neighborhood.geom_utm.area`):
I'll rebase away the WIP commits before merging.
Ensure you have at least one job in development that has a final status of COMPLETE. If you don't have a recent one, I'd suggest running a new analysis, as additional properties have been added (mileage).
Once you have at least one current analysis, simply run:
``` …
```
=> Generate analysis results CSV via management command

src/angularjs/src/app/places/detail/place-map.directive.js
Add a "None" layer option to the Destinations layer group so that a user can toggle the display of destinations. This option is selected by default.
So that we do not mess up the order in which the layer groups draw in the picker, we have to ensure that we add the "None" layer immediately before the remaining destinations layers. The group layer control doesn't give us a way to specify a particular order.
Opened:
https://github.com/ismyrnow/leaflet-groupedlayercontrol/issues/54
* View a completed analysis job's detail page. Ensure you can select the "None" destination option and that it displays no results.
Closes #542
=> Add None option to Destinations layer picker

src/angularjs/src/app/components/map/map.constants.js
See title.
* On bike detail page, set the overlay to "Bike Infrastructure" and ensure the legend matches the text requested in #543 
Closes #543
=> Tweak bike infrastructure legend text

src/analysis/scripts/detect_utm_zone.py
Fixes https://github.com/azavea/pfb-network-connectivity/issues/423 by implementing string formatting when reading the UTM zone of an input shapefile.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
Run detect_utm_zone.py using [ak.zip](https://github.com/azavea/pfb-network-connectivity/files/1730083/ak.zip)
Also tested with shapefile in UTM zone 10N and verified no regression for 2 digit UTM zones.
=> Add string formatting to handle single-digit UTM zones

Vagrantfile, src/angularjs/.eslintrc, src/angularjs/src/app/index.run.js, src/angularjs/src/index.html
Adds snippet, which by default sends a page view on load. Also added a basic handler to send a screen view event when the user successfully navigations to different app views. This event includes an "environment", determined by `$window.location.hostname`, since we don't have any sort of multi-environment configuration setup in this app.
A commit snuck in to fixup Ansible provisioning on Vagrant. Let me know if that causes issues.
1. Disable any ad blocker you may have configured in your browser
1. Load the page.
1. Filter your dev tools network tab by "Images" and ensure you see a bunch of `collect` requests fired like in the screenshot above.
1. If you have an ad blocker installed, re-enable it
1. Repeat steps 2 + 3 and verify that there are no application JS errors, although you may …
=> Add Google Analytics snippet

deployment/aws-batch/docker-compose.yml
In all environments, we fully configure the AWS
credentials via profile settings. So we don't need to
make the region available separately as an ENV variable.
Note that this variable was also incorrect. The correct
name for the ENV variable to set the region is
AWS_DEFAULT_PROFILE. See:
http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variables
Given the above, it seemed best to just remove this ENV var without replacing it with `AWS_DEFAULT_PROFILE`.
Follow the instructions in [deployment/README](./deployment/README.md#terraform) to deploy your current commit to staging. If your `pfb` AWS profile is configured correctly, with the region set in `.aws/config` and your access + secret keys in `.aws/credentials` then the deployment should still succeed, since the …
=> Remove unused and incorrect AWS_REGION variable

src/django/Dockerfile, src/django/pfb_analysis/filters.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py, src/django/requirements.txt, src/django/users/views.py
Bumps Django to the next minor version, 1.11, and updates Python dependencies.
Looks the same.  Also, I destroyed my instance so I don't have many neighborhoods...
Re Django:
- The Azavea Django base container comes in two flavors for 1.11, "-slim" and "-alpine". I picked "-slim" because it comes with `gcc` installed, which is necessary for installing fiona.
- As the comment indicates, the Django and psycopg2 versions in the requirements file are used by other containers that install Django to push status updates to the Django container via management commands. This updates those versions to keep them in sync with what's installed in the base Django container.
Re dependencies:
- For `django-amazon-ses`, moving to version 1.0.0 would require some changes, so I upgraded to the last version …
=> Upgrade Django to 1.11

src/analysis/scripts/download_osm_extract.py
I verified that OSM caching works correctly on staging, per issue #567.
First, I spun up 2 more worker instances for a total of 3 (there was one running already). Then I created jobs, through the "Run Analysis" form on the admin site, for:
- Stockton, CA
- Bakersfield, CA
- Madison, WI
- Colorado Springs, CO
The first started immediately on the preexisting worker, the next two shortly thereafter once the additional workers had finished initializing yet, and the last ran after the first had finished.  The Stockton job downloaded the California OSM extract to S3 and the Bakersfield job downloaded it from S3 about 4 minutes later.  The WI and CO jobs downloaded their respective OSM extracts from Geofabrik and uploaded them to S3.
After all that was done, to trigger the download locking …
=> Verify OSM caching, switch the 'waiting on lockfile' message to INFO level

Vagrantfile, deployment/vagrant/install_pip.sh
#581 added a fix for ensuring that local Ansible gets installed correctly, which exposed a new issue where pip isn't installed by default to install the requisite pip packages added to a shell provisioner. This PR adds another shell provisioner that ensures that pip is installed before doing anything else in the VM.
The install_pip.sh script installs pip using the same method described by the Ansible local provisioner docs for best compatibility. The Ansible `pip` directive targets `/usr/local/bin/pip2` instead of `/usr/local/bin/pip`, but running a `pip freeze` after provisioning completes shows all packages installed by Ansible, so the versions are correctly associated.
```
vagrant destroy
./scripts/setup
```
Ensure provisioning completes successfully and that you can start a server …
=> Manually install pip before attempting to install packages

Vagrantfile
Use NFS v3 when mounting the share on a linux host.
Matches mount options used in other projects.
Fixes #596.
* NFS share should still mount on other hosts
* NFS share should mount on recent Ubuntu hosts
=> Modify VM NFS mount options

docker-compose.yml, src/analysis/scripts/export_connectivity.sh, src/analysis/scripts/utils.sh, src/django/pfb_analysis/management/commands/import_results_shapefiles.py
This PR Includes job id in the shapefile import management
command and runs the command during analysis export.
This will slow down analysis jobs but not signficantly.
Jobs should run far enough apart that it doesn't lead
to excessive DB load during a large analysis run (but
this is untested).
While inefficient because we need to re-download the
shapefile we just uploaded, the shapefile sizes aren't
huge and it's cleaner than attempting to include
custom logic in bash to directly copy data from the
analysis DB to the app DB.
Checkout branch then rebuild analysis VM with `docker-compose build analysis`.
Trigger a new job via the PFB web admin UI, then run the job via the command printed to the docker console. It should succeed, and you should have NeighborhoodWaysResults and …
=> Add Job ID to shapefile export

src/django/pfb_analysis/models.py, src/django/pfb_network_connectivity/settings.py, src/tilegarden/src/api.js, src/tilegarden/src/tiler.js, src/tilegarden/src/util/layer-filter.js, src/tilegarden/src/util/param-filter.js, src/tilegarden/src/util/xml-tools.js, src/tilegarden/tests/layer-filter.test.js
Switches to using the Tilegarden tiler in development.  Specifically:
- Adds a `job_id` path parameter to the Tilegarden route
- Moves the `config` parameter out of the querystring and into the path
- Changes `AnalysisJob.tile_urls` to return Tilegarden endpoints as tile URLs rather than the S3 ones
- There was already a syntax for applying arbitrary filters, but it's [pretty complicated](https://github.com/azavea/tilegarden#client-specified-filtering) and relies on querystring parameters, which could [make it hard to add S3 caching](https://github.com/azavea/tilegarden/issues/126#issuecomment-441776311).
- I considered removing the `layers` filtering, since we're not using it, but 1) that would have made these changes particularly hard to …
=> Enable Tilegarden tiler and add job_id filtering

src/django/pfb_analysis/management/commands/import_results_shapefiles.py
Exclude null readings from the shapefile interpreted as zeroes by removing any Census block results
outside the neighborhood bounds with a zero overall score (actually should be null).
Workaround for `LayerMapping` not distinguishing between unset/null and zero in the shapefile.
Shapefiles do not officially support null representation.
Lower Manhattan analysis with water blocks removed. Zero-scored blocks in the interior have been preserved, as have Census blocks with scores not entirely within the neighborhood bounds.
On inspecting the shapefile on a host with GDAL 2.2 and the latest `fiona` version, nulls appear to be correctly recognized. However, in the docker container, they were not (all read as zeroes). Using `fiona` presents other drawbacks as well: it's significantly slower, …
=> Mask imported Census blocks to neighborhood bounds

scripts/server, scripts/update
Previously, the `django-q` service was being built implicitly by the call to `docker-compose up` in `scripts/server`, and was missing from the list of images to build in `scripts/update`.
Adjust `scripts/update` to build this service explicitly, and alter `scripts/server` to run `docker-compose up --build` so that it will always build fresh images before running the dev server.
- For more context on these changes, see https://github.com/azavea/pfb-network-connectivity/issues/616#issuecomment-446320036.
* Shell into the VM with `vagrant ssh`
* Remove the `django-q` image with `docker rmi django-q:latest`
* Run `./scripts/update` and confirm that `django-q:latest` gets built
* Run `./scripts/server` and confirm that `docker-compose up` rebuilds all images before running the services
Fixes …
=> Build the django-q container in scripts/update

src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/tasks.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py
Run a dummy `django-q` task on creating a local analysis upload task in the API.
The endpoint already existed, so this adds some validation and a dummy task.
`django-q` processing the upload in the logs:
Successful POST response:
Attempting to POST with a neighborhood UUID that is a valid UUID, but matches no neighborhood:
* Rebuild containers to address #616, if necessary
* Post a neighborhood UUID and URL to http://localhost:9200/api/local_upload_tasks/
* Should create an `AnalysisLocalUploadTask` for the matching neighborhood, with the URL
* `django_q` should log the (dummy) task processing
* API response should include expected fields and status
* Attempting to post invalid data should return an appropriate error
Closes #618
=> Feature/kak/add analysis upload endpoint#618

src/tilemaker/Dockerfile
Address GPG keyserver timeout issues on `tilemaker` container build.
* Clean out local docker images
* `./scripts/update` should succeed reliably without GPG keyserver timeouts
Fixes #630.
=> Switch GPG keyservers used in tilemaker docker build

deployment/terraform/docker-compose.yml, scripts/infra
Builds to develop are failing because I updated Terraform state using Terraform v0.9.6, but the Jenkins box on CI runs v0.9.3. Instead of relying on the Terraform version installed on the host,
run Terraform from a Quay image to ensure that versions are consistent across all environments.
Test this PR by running a deployment manually on your machine:
* Shell into the VM with `vagrant ssh`
* Export required env vars for deployment:
```
export GIT_COMMIT=$(git rev-parse --short HEAD)`
export ENVIRONMENT="staging"`
export PFB_AWS_ECR_ENDPOINT="950872791630.dkr.ecr.us-east-1.amazonaws.com"
export PFB_SETTINGS_BUCKET="staging-pfb-config-us-east-1"
```
* Run `./scripts/infra plan` to plan the deployment (only the task definitions and ECS services should change)
* Run `./scripts/infra apply` to …
=> Use Terraform image to run infrastructure updates

src/angularjs/src/app/places/list/places-list.controller.js
Separately request neighborhood data for comparison places.
Fixes comparison places not in current page of places on list view being lost on reloading list view.
Original issue cannot be reproduced locally without having more than one page of analysis results to display.
* `./scripts/update`
* Visit front-end site at dynamically loaded port (not nginx) http://localhost:9301
* Navigate between comparison page, details, and list, adding places to compare
* Reload list page with places to compare set
* Comparison place list in list view should be retained as expected
Fixes #523
=> Fix comparison places not on current page being lost

scripts/infra
Previously, calls to `rm -rf .terraform` during `scripts/infra` on CI were being run as the Jenkins user. This would often fail because the `.terraform` directory had been created by a Docker Compose call, and so was owned by `root`. Use Docker Compose to remove the directory to avoid permissions errors.
* See [this build](http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/job/develop/255/) for an example of the bug.
* `ssh` into the Jenkins instance
* Run `sudo su - jenkins`
* `cd` into the `develop` workspace
* Run `cd deployment/terraform`
* Run `rm -rf .terraform` and confirm the command throws a permissions error
* Copy and run the command from the diff in this PR and confirm that the directory gets deleted
Connects #633
=> Use Docker Compose to remove terraform state in scripts/infra

src/django/pfb_analysis/management/commands/load_overall_scores.py, src/django/pfb_analysis/tasks.py
Extract, validate, and upload local analysis results from provided URL in task.
A completed job:
Re-imported neighborhood ways and Census blocks for that job:
The files uploaded for the job to S3:
Error message returned on attempting to upload a zip file missing results:
* Upload local analysis results to a publicly accessible URL (or use [mine](https://s3.amazonaws.com/kat-pfb-storage-us-east-1/germantown_results.zip))
* Create a local analysis upload task at http://localhost:9200/api/local_upload_tasks/
* Get the job UUID from the returned upload task JSON
* Check all 19 results file are on S3 in the results directory named like: `https://s3.console.aws.amazon.com/s3/buckets/{$USER}-pfb-storage-us-east-1/results/{JOB_ID}/`
* Check in the Django console that Census block and neighborhood …
=> Feature/kak/import local anaysis jobs#617

src/analysis/scripts/export_connectivity.sh
Do not attempt to download shapefile for re-import before shapefile uploaded to S3.
The geometry re-import added [here](https://github.com/azavea/pfb-network-connectivity/commit/68c9d6e596019e136d2677767e9bbc46a9e5fc28#diff-0d62f360dfca1dcdc47238568110d5a1R179) was attempting to re-import a file from S3 before it got uploaded to S3 in the block below.
* Start a local analysis job
* Run the analysis job command output to console
* Job should complete successfully
* Analysis results should show in UI as expected
Fixes #637.
=> Fix local analysis run

src/angularjs/src/app/components/countries.service.js, src/angularjs/src/app/neighborhoods/create/neighborhoods-create.controller.js, src/angularjs/src/app/neighborhoods/create/neighborhoods-create.html, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.html, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/urls.py
Adds country field to Angular administrative web UI for neighborhoods.
State required when US selected:
State hidden when non-US country selected:
* Create new neighborhoods via web admin UI at http://localhost:9301/#/admin/neighborhoods/
* Country/state interactions should work as expected (state required for US, not set for non-US)
* Country should be listed in the neighborhood list view
Closes #627
=> Feature/kak/neighborhood country ui#627

src/angularjs/src/app/analysis-jobs/detail/analysis-jobs-detail.html, src/angularjs/src/app/analysis-jobs/import/analysis-jobs-import.controller.js, src/angularjs/src/app/analysis-jobs/import/analysis-jobs-import.html, src/angularjs/src/app/analysis-jobs/import/module.js, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/analysis-jobs/module.js, src/angularjs/src/app/components/analysis-jobs/analysis-jobs.service.js, src/angularjs/src/app/index.route.js
Add view at /admin/analysis-jobs/import to import
existing analysis results.
New button:
Page:
* Go to admin UI analysis job page [here](http://localhost:9301/#/admin/analysis-jobs/)
* Click to import analysis should go to new import page
* Should be able to start analysis import
* Should redirect to analysis job list page after submit
Closes #647.
=> Add analysis import admin UI

common.yml, scripts/clear-tile-cache, src/tilegarden/.env.dev, src/tilegarden/.eslintrc.json, src/tilegarden/src/api.js, src/tilegarden/tests/api.test.js
Adds a step in the tile generation process where it checks for a `PFB_TILEGARDEN_CACHE_BUCKET` variable in the environment and, if it's set, writes the tile into that bucket, using the request path as the key.
Currently there's no way to serve the tiles from cache.  #634 covers that part.
Also adds a script to clear all files in the configured cache bucket.  I'm not sure that will be the way to do it in deployed environments (where it's harder to get a shell, and where the number of items might make the "change settings to make all objects expire, change settings back" deletion strategy preferable), but it seems useful in development.
```
vagrant@pfb-network-connectivity:/vagrant$ aws s3 ls --recursive s3://dev-pfb-tilecache-us-east-1/
2019-01-23 17:00:57        334 …
```
=> Write tiles to S3 cache

src/django/pfb_analysis/views.py
Remove failed `django-q` tasks from the task queue, instead of retrying indefinitely. Applies to both analysis import tasks and batch analysis job tasks.
A single task failing in the logs:
Limiting the number of retries to a low number might be preferable to limiting to one attempt, in case of some intermittent failure. However, `django-q` appears to not offer retry attempt count limits as a feature.
Tasks that fail currently have their related Django model object marked with `ERROR` status, but the `django-q` task would continue to retry, even after calling `delete` on the queue task. This change will not stop any existing failing queued tasks from continuing to retry, but will cause new tasks to not retry after failure.
* Create an analysis upload task that will fail (as with a URL that …
=> Feature/kak/cancel q tasks#671

src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.html, src/angularjs/src/app/users/list/users-list.html
It turns out fixing a style syntax error in [PR 655](https://github.com/azavea/pfb-network-connectivity/pull/655/files#diff-5645138bbcfd38020bf72c8203017f60L43) caused that style to start getting applied, but when combined with the fact that the pagination buttons in the admin were getting the default
`color` style from `btn` (because they were using a non-existent `btn-success` class), made them all but disappear.
This changes the class to `btn-default`, which is the same one used by the pagination buttons on the public-facing site.
Go to http://localhost:9301/#/admin/neighborhoods/, http://localhost:9301/#/admin/analysis-jobs/, and http://localhost:9301/#/admin/users/.  There should be pagination buttons at the bottom that are dark if active or lighter if disabled but clearly visible …
=> Fix invisible admin pagination buttons

Jenkinsfile
Fix docker port allocation issue by only running one build at a time.
Fixes #670.
=> Disable concurrent CI builds

Jenkinsfile
Use the `test/` branch prefix to trigger automatic deployments to staging. This allows us to more easily test things in staging without having to merge into `develop`. Afterwards, re-triggering a `develop` build wipes the `test/` branch contents away.
Resolves #593 
First, checkout this PR's branch:
```bash
$ git checkout feature/jrb/add-test-branch-prefix
```
Now, create and push up a new branch based off this PR:
```bash
$ git branch test/jrb/test-branch-prefix-pr
$ git push -u origin test/jrb/test-branch-prefix-pr
```
See that Jenkins kicks off a new build which cycles Terraform, etc:
http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/job/test%252Fjrb%252Ftest-branch-prefix-pr/1/console
=> Publish to staging with test/ branch prefix

src/django/pfb_analysis/serializers.py
Make local upload task read-only on serializer.
* Should be able to create a job [here](http://localhost:9301/#/admin/analysis-jobs/create/) 
* Should not get error response from analysis job API endpoint
Fixes #683.
=> Fix creating new analysis jobs

deployment/ansible/roles/pfb.docker/tasks/main.yml
Due to an upstream bug in the `ansible-pip` role (https://github.com/azavea/ansible-pip/issues/12), the VM installs pip 19 instead of pip 9. As of pip 10, pip [no longer has support for uninstalling system packages](https://github.com/pypa/pip/issues/5247), which was preventing it from installing docker-compose. In order to get around this bug, instruct pip to [ignore installed packages](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-i) when installing docker-compose, effectively reverting the behavior to what it was in pip 9.
* For a detailed discussion of the pip issue, see: https://github.com/pypa/pip/issues/5247 And for the recommended solution, see: https://github.com/blockstack/blockstack-core/issues/504
* It seems like the biggest downside to this approach is that …
=> Use pip --ignore-installed flag when installing docker-compose

src/django/pfb_analysis/tasks.py
Fixes round-trip export/import of results by not requiring the GeoJSON version of the Census blocks results, which are imported instead as the Shapefile version; the GeoJSON file, though present in the local analysis results directory on the host machine, is not available for download through the UI.
I'm not sure why the GeoJSON file is present, and so I'm not entirely confident that it is redundant for import.
- Download the files from the web admin UI page for a completed analysis job on production or staging
- Zip the files together and upload them to a publicly accessible URL
- Locally (on this branch) create an import task pointing to the zipped results file
- Import should succeed and display results that match the original
Closes #687.
=> Do not require Census blocks GeoJSON to import

common.yml, deployment/terraform/app.tf, deployment/terraform/task-definitions/app.json, deployment/terraform/task-definitions/django-q.json, deployment/terraform/task-definitions/management.json, deployment/terraform/variables.tf, src/django/pfb_analysis/models.py, src/django/pfb_analysis/tasks.py, src/django/pfb_network_connectivity/settings.py
As noted on #694, there are advantages to being able to easily switch between the tilemaker/S3 tiler and Tilegarden.  Also, per https://github.com/azavea/pfb-network-connectivity/issues/611#issuecomment-454157314, there was a bit more to do to fully integrate Tilegarden.
This switches the toggling behavior to use a new variable, `PFB_USE_TILEGARDEN`, and changes the analysis model to check it to determine both what tile URLs to send to the front-end and what to do after its analysis job runs--generate tiles with `tilemaker` if Tilegarden is disabled, mark the job complete if it's enabled.
This should make it easy to stay with `tilemaker` (by setting the variable to `false`), use Tilegarden immediately (by setting it to `true`), or start with the former then switch to the latter.  The …
=> Expand implementation of tilegarden toggle

scripts/test
Make sure that the `docker-compose run` commands that call linters make use of the `--no-deps` flag in order to avoid bringing up the Django service and causing port collisions on CI.
In https://github.com/azavea/operations/issues/284 we had speculated that the port collision issue might be systemic to our CI config, since it affects both PFB and OAR. However, after looking at the build failures in detail I think that we were running into different issues in both PRs, both caused by separate failures to be careful about which Compose commands allocate ports and which don't. As such, neither PR makes major changes to the way we configure or run Compose on CI. 
* Start a CI job for this PR by selecting `Build now` on http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectiv …
=> Fix port collisions on CI

src/django/pfb_network_connectivity/settings.py
Turns out Terraform converts 'true' to '1', but [the docs](https://www.terraform.io/docs/configuration/variables.html#booleans) say to keep using 'true' for future compatibility.
So this makes the Django setting that reads it in accept either.
I noticed this because the deployment of #696 made staging switch back to S3 tiles.  I pushed a `test/` branch to confirm that this fixes it.
=> Match either 'true' or '1' for USE_TILEGARDEN variable

deployment/README.md, docker-compose.test.yml, scripts/infra, src/tilegarden/.gitignore, src/tilegarden/package.json
Instead of mounting the Claudia config file directly into the Tilegarden container during deployments, move it into its own directory and mount that directory instead. This allows Docker to create the directory if it doesn't exist yet, which lets us simplify initial deployments of new Tilegarden instances.
See:
* https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only
* Shell into the VM
* Pull down the staging `.env` file from S3:
```console
$ aws s3 cp s3://staging-pfb-config-us-east-1/tilegarden/.env ./src/tilegarden/.env
```
* Edit `.env` file to change `PROJECT_NAME` to something different for testing, e.g. `pfbTilegardenTestingNewConfig`
* Create new test Tilegarden instance:
```console
vagrant@pfb-network-connectivity:/vagrant$ docker-compose \
-f …
```
=> Improve organization of claudia configs for easier deploys

src/angularjs/src/app/home/neighborhood-map.directive.js, src/angularjs/src/app/home/neighborhood-map.html
To support non-US cities, makes the map on the home page zoom to include all features and removes the word "Nationwide" from the caption.
Turns out we already have places in AK, HI, and PR, which makes it zoom pretty wide even without international cities.
- As you can see in the screenshot above, it likes to cut off the northernmost marker. I tried adding padding to prevent that, but it zoomed out too far.  I didn't try to tune the padding or pursue it further because it seems like not that big a deal to me.
- I tried briefly to find any other spots where the US-only assumption is encoded in a user-visible way, but didn't come up with any.
Load the home page.  The map should zoom to fit all the neighborhoods you have defined in your database.
Resolves #704
=> Zoom to all places on landing page map and remove 'Nationwide'

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Fills out and spruces up the CHANGELOG:
- Adds comparison links
- Adds headings for all the past release tags (with dates and comparison links but not any details about what they included)
- Tweaks the 0.9.0 entry to use subsections like the 0.7.0 one (and like the Keep A Changelog pattern)
- Adds a (one-item) checklist to the PR template to remind us to update the changelog
I also changed `Connects` to `Resolves` in the PR template to avoid "I merged the PR, why didn't the related issue get closed?" situations.
- Take a look: https://github.com/azavea/pfb-network-connectivity/blob/feature/kjh/improve-changelog/CHANGELOG.md
- Follow a link or two and confirm they point at the right thing
Resolves #657
=> Improve changelog

CHANGELOG.md, deployment/README.md, src/tilegarden/package.json, src/tilegarden/src/api.js, src/tilegarden/yarn.lock
Since the Tilegarden Lambda functions are inside a VPC (which they need to be, since they talk to the database), [their cold start times are bad](https://medium.freecodecamp.org/lambda-vpc-cold-starts-a-latency-killer-5408323278dd).  This adds the [`lambda-warmer`](https://github.com/jeremydaly/lambda-warmer) package and configures the Lambda function's entrypoint to handle the type of invocations that trigger it.
I initially did something much more complicated (see [branch](https://github.com/azavea/pfb-network-connectivity/tree/feature/kjh/lambda-warming-endpoint)), involving a warming endpoint that could be triggered from outside and would in turn trigger a `lambda-warmer` event.  This was based on the fact that 
- to be effective, we'll need to have a decent number of workers warmed …
=> Enable Lambda warming on Tilegarden function

CHANGELOG.md, deployment/README.md, deployment/terraform/iam.tf, src/tilegarden/.env.example
The Tilegarden Lambda function needs some permissions, specifically
- write logs
- attach to a VPC
- write to the S3 cache
- invoke itself for warming
If you don't provide a role to Claudia.js, it makes one that has the first two, but since the other two are for custom Tilegarden functionality, they need to be added.  The most straightforward way to do that is to define the whole role in Terraform and just hand it to Claudia.js in the .env file.
So this adds the Terraform code to do that, moves the `LAMBDA_ROLE` variable out of the "Optional" section of the .env.example file, and removes the section from the deployment instructions saying you have to do it manually.
I ran terraform `plan` and `apply` manually for staging, so here's a screenshot of the created role:
- I put a few extra …
=> Define Tilegarden executor role in Terraform config

README.LOCAL-ANALYSIS.md
Adds a section about uploading local analysis results to the end of the "Running the Analysis Locally" README page.
I was initially thinking this should go in the "PFB Batch Analysis Documentation" Google doc, but that's very focused on the process of doing batch uploads and managing the AWS Batch environment.  The "Running the Analysis Locally" guide is much more closely related to importing.
- Read [the new section of README.LOCAL_ANALYSIS](https://github.com/azavea/pfb-network-connectivity/blob/feature/kjh/local-upload-readme-section/README.LOCAL-ANALYSIS.md#importing-local-analysis-results-into-the-bna-site).  Make sure it is correct and makes sense.
~- [ ] Add entry to CHANGELOG.md~
Resolves #705
=> Add a section to the local analysis readme about uploading results

deployment/README.md
Adds a section documenting the `tfvars` config file.  The `infra` steps assume it's in place and up to date, but there was no mention of creating or updating it.
- Read and critique
Resolves #658
=> Add deployment documentation section about setting up tfvars

deployment/README.md, deployment/terraform/iam.tf, deployment/terraform/variables.tf, src/tilegarden/.env.example, src/tilegarden/scripts/deploy-new
Adds a tfvar for the name of the Tilegarden Lambda function and uses it to restrict the Lambda execution permission on the TilegardenExecutor role.
See [discussion on PR #719](https://github.com/azavea/pfb-network-connectivity/pull/719#discussion_r260855692)
Also
- Uses the tfvar to set the name of the executor role.
- Renames the variable on the Tilegarden side to `LAMBDA_FUNCTION_NAME`, since that's what it's used for.
- Removes the `LAMBDA_ROLE` variable from the Tilegarden .env example and uses the `LAMBDA_FUNCTION_NAME` value with 'Executor' appended to match what Terraform does when creating it.
What this does *not* do is resolve #714 by incorporating the Lambda-warming scheduled task into Terraform.  It turns out giving CloudWatch the permission to invoke a Lambda function is done …
=> Add Terraform var for Tilegarden function name

CHANGELOG.md, deployment/README.md, scripts/infra
Adds a section to the deployment documentation about how to safely apply migrations.  Since in some cases migrations need to be applied before the API service is updated, also adds a pair of commands to `infra` to deploy only the management task, so that migrations can be run before the matching API service is updated and starts handling requests that might rely on the schema being updated.
```
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.
Your plan was also saved to the path below. Call …
```
=> Add documentation section and infra commands for migration

src/angularjs/src/app/neighborhoods/create/neighborhoods-create.controller.js, src/angularjs/src/app/neighborhoods/create/neighborhoods-create.html, src/django/pfb_analysis/countries.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py, src/django/requirements.txt
Main changes:
- Adds a config dictionary in settings to record what countries we want to track subdivisions for.
- Adds the `pycountry` package, which provides subdivisions
- Uses the `pycountry` and the config to add subdivisions to the list returned by the `countries` endpoint, only for the countries whitelisted in the config.
Incidental changes:
- Renames the country abbreviation field from `abbr` to `alpha_2`. That's what it's called in pycountry. Not that we have to be bound by that, but I like it better--more explicit.
This leaves the `state` endpoint alone. I think it should go away, but that seems to fall under issue #732.
Though it adds `pycountry`, this doesn't remove `django-countries` or `us`. It does reduce the usage of `us`, so I think we should be able to remove that by the …
=> Add subdivisions to 'countries' list, and country config

CHANGELOG.md, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js
Removes the option to sort places by state then name, which had been the default.  Now the default is alphabetical by place name across all states and countries.
(Issue #734 will add filtering to solve the problem of finding a place by country or state.)
This also includes a small code refactor to the next and previous buttons.  As noted in the commit message, they tripped me up for a minute and then bothered me enough to spend a few minutes reconfiguring them a bit to reduce moving parts and repetition.  I believe they're functionally unchanged.
- Load the places list, behold the alphabetical sorting.
- Use the "Previous" and "Next" buttons (set `REST_FRAMEWORK['PAGE_SIZE']` to something small if you don't have enough places for the default page size) and confirm that they still work as …
=> Sort places by name, remove sorting by state

CHANGELOG.md, src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.controller.js, src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.html, src/angularjs/src/app/analysis-jobs/import/analysis-jobs-import.controller.js, src/angularjs/src/app/analysis-jobs/import/analysis-jobs-import.html, src/angularjs/src/app/home/home.html, src/angularjs/src/app/neighborhoods/create/neighborhoods-create.html, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.html, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/detail/places-detail.html, src/angularjs/src/app/places/list/place-list.html, src/django/pfb_analysis/countries.py, src/django/pfb_analysis/models.py, src/django/pfb_analysis/serializers.py, src/django/pfb_analysis/views.py, src/django/pfb_network_connectivity/settings.py
Changes the way neighborhood labels are formatted, moving it partly out of the front-end templates and into the API.  They'll now show up as "Label, ST, CO", where ST is the state/province abbreviation if there is one and CO is the 2-letter country code.
I removed the label template from the `COUNTRY_CONFIG` dictionary because the desired label format is simple enough that it's not necessary.  It always uses abbreviations, and always includes a state if there is one.
This means that special cases like running an analysis for a whole region should be handled by leaving the State/Province field blank when creating the neighborhood.  I.e. the neighborhood for the whole province of Limburg, Netherlands, should be entered as (label='Limburg', state_abbrev='', country='NL').  This is …
=> Format neighborhood labels to include state/province and country

CHANGELOG.md, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js, src/django/pfb_analysis/views.py
Adds country and state/province filtering to the places list on the public site.  Both are droplists, populated by the `countries` endpoint.  The "state/province" list is disabled when there's no country filter selected or the selected country has no states to filter on.
Rather than present a massive list of countries, almost all of which would be irrelevant because there are no places there, I added a parameter to the `countries` view that makes it return only countries and subdivisions for which there is a visible result--i.e. ones for which there's at least one non-hidden Neighborhood with at least one completed job.
- Putting a bunch of logic defining what it means for a `Neighborhood` to be visible inside the `CountriesView` seems kind of awkward, so I initially created a custom …
=> Filter Places list by country and state

README.LOCAL-ANALYSIS.md
A small change to the local analysis documentation to clarify that the `AWS_PROFILE` variable is only relevant when `PFB_JOB_ID` is also set, i.e. when running a local analysis for a job created within a local app instance.
=> Clarify purpose of AWS_PROFILE in local analysis readme

CHANGELOG.md, src/analysis/Dockerfile, src/analysis/README.md, src/analysis/scripts/detect_utm_zone.py, src/analysis/scripts/download_osm_extract.py
Updates the Python scripts in `/src/analysis` to Python 3.
Although backward compatibility with Python2 was not a requirement, and the code required only minimal changes to achieve Python3 compatibility, I discovered that the import statements necessary to achieve backwards compatibility can serve a useful signaling function to both automated and human readers that the code has been audited for Py3 compatibility. For example, performing automated conversion on `detect_utm_zone.py` initially resulted in the following diff:
```
--- scripts/detect_utm_zone.py	(original)
+++ scripts/detect_utm_zone.py	(refactored)
@@ -5,6 +5,8 @@
Based on https://github.com/jbranigan/geo-scripts-python/blob/master/latlng2utm/detect-utm-zone.py
"""
from __future__ import print_function
+from __future__ import …
```
=> Migrates analysis scripts to Python 3

Vagrantfile
When doing the Python upgrade I changed `ansible.install_mode = "pip"` to `pip3` (43cd67a2). But that's not actually a valid value of that variable (see https://www.vagrantup.com/docs/provisioning/ansible_local.html#install_mode).  Which I guess made Vagrant silently ignore it and start installing Ansible with `apt`. So once the Ansible version in the apt repository changed, that caused provisioning to fail because `ansible.version` didn't match the system-installed version. Not realizing it was installing Ansible the wrong way, I resolved that issue by removing the version specifier (eb8d99ba). But now that the version of Ansible in the repo has been upgraded to 2.9, there's a new crash due to breaking changes to the ansible file spec.
So this sets `ansible.install_mode` back to `"pip"` …
=> Restore ansible version specifier in Vagrantfile

CHANGELOG.md, src/django/pfb_analysis/models.py
Now that we can delete neighborhoods--which means we can also delete analysis jobs, since they get deleted along with their neighborhood--we run the risk of creating a mess of orphaned files on S3.  The Neighborhood model keeps its boundary file on S3, and the results of the AnalysisJob processing are stored on S3 as well.
This adds post-delete handlers for those two models to delete the files from S3 after the instances have been deleted. For Neighborhood, which uses a `FileField`, it's just a matter of calling `.delete()` on it.  AnalysisJob doesn't have a field to track its own assets, but it does know the S3 path where they live, so we can use that to delete them with boto3.
Note: to make it easy to see files appearing and disappearing on S3, I decided to clear out the `results/` path …
=> Delete Neighborhood and AnalysisJob files from S3 on instance deletion

CHANGELOG.md, src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.controller.js, src/angularjs/src/app/index.module.js, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.controller.js, src/angularjs/src/app/utils/module.js, src/angularjs/src/app/utils/parse-errors.js, src/django/pfb_analysis/models.py, src/django/pfb_analysis/serializers.py
The error message being shown there was a problem creating a neighborhood was a mess--the exception gets raised in the model's `save` method and wasn't getting translated into an exception that Django Rest Framework can translate into an informative response, so it was coming back as a generic 500 error, with its content in HTML.  Then the front-end was treating that HTML string as a `{fieldname: error message}` object and trying to print each property.  Since a string can be cast to an array and an array can be treated as an object with integer properties, what we got was a each letter of the response preceded by its index.  Wacky.  And not useful.
So this adjusts the error parsing to account for that case.  It still extracts field errors and lists them in the error message, but only if …
=> Clean up neighborhood management error messages

CHANGELOG.md, src/angularjs/src/app/components/map/map.directive.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.directive.js, src/angularjs/src/app/components/thumbnail-map/thumbnail-map.html, src/angularjs/src/app/home/neighborhood-map.directive.js, src/angularjs/src/app/home/neighborhood-map.html, src/angularjs/src/app/neighborhoods/detail/neighborhood-detail-map.directive.js, src/angularjs/src/app/neighborhoods/detail/neighborhood-detail-map.html, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.html, src/angularjs/src/app/places/detail/place-map.directive.js, src/angularjs/src/app/places/detail/place-map.html, src/angularjs/src/app/places/list/places-list-map-directive.js, src/angularjs/src/app/places/list/places-list-map.html, src/angularjs/src/styles/pages/_mapping.scss, src/django/pfb_analysis/views.py
Adds a map to the bottom of the "Edit Neighborhood Details" view.  It's for informational purposes only, not editable, but since currently there's no way to see a neighborhood's geometry without having analysis results for it and loading the boundary layer on the public site, it seems useful.
It's a copy-modify of the thumbnail map directive, since they're pretty similar, but not necessarily similar enough that it makes sense to adapt a single directive to work in both places.
It uses the existing `neighborhoods_bounds_geojson` endpoint, but modifies it slightly to take a `detailed` parameter.  The simplified geometry that makes works well for the thumbnail looks jagged on a larger map.  And since we're only loading one geometry at a time rather than a whole list of them, the larger size …
=> Add map preview to neighborhood editing page

CHANGELOG.md, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.controller.js, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.html, src/django/pfb_analysis/models.py
I spun issue #779 off of #766 because it didn't "just work" and I wasn't sure what it would take to get it working.  This gets it working.  The file field is optional in editing mode, but if it's set, the new boundary file will be used to replace the existing neighborhood boundary.
Resolves #779.
- This builds on the branch for PR #781 (map preview), so I pointed the PR at that.  It's not actually dependent, but it's really nice to have the preview map to be able to easily see that saving worked.
- It was pretty straightforward to hook into the existing model functionality for saving the boundary, but I would have preferred to do it closer to the edge--i.e. in the view or serializer rather than way down in the model.  But there are a bunch of steps in between, and to pass an `override` …
=> Allow replacing geometry when editing neighborhoods

src/analysis/import/import_jobs.sh
The BNA retrieves 2014 LODES data from the Census (2013 data if 2014 is not available for a state). 2017 or 2016 data are now available for all states, so this PR updates the data retrieval to use the latest data available for each state.
The LODES automated data retrieval has failed frequently lately in testing, apparently due to problems on the Census Bureau's end. When the data is manually downloaded and provided to the BNA it runs fine.
* Run BNA for any U.S. state.
* For all U.S. states except Alaska and South Dakota, analysis will proceed as usual and produce Employment score at finish.
* For Alaska and South Dakota, analysis will fail to find 2017 data and will instead default to downloading 2016 data, then proceed as usual.
=> Update LODES data retrieval to latest available (2017/2016)

src/analysis/features/functional_class.sql
Currently, service roads and footways are labeled as bike paths in the BNA if they have the tag "bicycle=designated." If they do not have that tag they are not considered bikeable ways, i.e. neither high nor low stress. This PR adds "yes" and "permissive" to the acceptable values for the "bicycle" tag, enabling a wider range of ways to be considered bike paths and aligning with the acceptable values for the "living street" functional class. This change ensures designated bikeways that are also service roads or footways are not excluded from the analysis. As before, if service roads and footways do not have any "bicycle" tag at all they are excluded from the network.
BNA results for Madison, Wisconsin show a lakefront path ending abruptly. 
When the "bicycle=yes" tag is allowed, the path …
=> Expand bicycle permissions accepted

CHANGELOG.md, src/django/requirements.txt
The CI build of develop [started failing after release 0.12.0](http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/job/develop/355/).
It's saying "pg_config executable not found." and "pg_config is required to build psycopg2 from source."
I'm not sure why this is coming up now, since the requirements file hasn't been changed since the last successful `develop` builds.  But here we are.
The error message also says "If you prefer to avoid building psycopg2 from source, please install the PyPI 'psycopg2-binary' package instead."  So I switched to that.
I also bumped the patch versions of Django and psycopg2 by 1 (to 2.2.9 and 2.8.4, respectively), since there's no reason not to and [the Django fix](https://docs.djangoproject.com/en/2.2/releases/2.2.9/), at least, …
=> Switch to psycopg2-binary to resolve build failure

src/analysis/connectivity/access_colleges.sql, src/analysis/connectivity/access_community_centers.sql, src/analysis/connectivity/access_dentists.sql, src/analysis/connectivity/access_doctors.sql, src/analysis/connectivity/access_hospitals.sql, src/analysis/connectivity/access_parks.sql, src/analysis/connectivity/access_pharmacies.sql, src/analysis/connectivity/access_retail.sql, src/analysis/connectivity/access_schools.sql, src/analysis/connectivity/access_social_services.sql, src/analysis/connectivity/access_supermarkets.sql, src/analysis/connectivity/access_transit.sql, src/analysis/connectivity/access_universities.sql
When the user clicks on a destination in the BNA map "pop low stress," "pop high stress," and "pop score" values appear in the pop-up. For destinations retrieved from OSM as points (single nodes) residing within a single census block area, these values are accurate. For destinations retrieved from OSM as polygons that overlap multiple census blocks, these values are inaccurate. For single block destinations these values are accurate because they sum the population in all blocks within the bikeshed. For multi-block destinations these values are incorrect because they repeat the summation of the bikeshed population for every destination block without distinguishing between blocks that have already been counted. In the fixes implemented here, only the population of each **unique** block in …
=> Revise calculation of population scores for destinations

CHANGELOG.md, deployment/ansible/group_vars/all.example, deployment/ansible/roles.yml
Upgrades the [Ansible Docker](https://github.com/azavea/ansible-docker) module to `5.0.0`, which uses the [non-deprecated `download.docker.com` repository URL](https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/). Also upgrades Docker to `18.*`, the latest version available in the main repo and the version currently running on ECS; and Docker Compose to `1.23.*`, the latest version that will work with the current VM configuration.
I upgraded Docker Compose to `1.23.*`, which is not the most recent version. Upgrading to `1.24.*` or `1.25.*` resulted in a segmentation fault for any subsequent step. I didn't dig very far into the root cause of this problem and instead created #799 to track it.
* Run `scripts/setup` and verify that VM is created successfully.
* Run …
=> Upgrade ansible-docker, Docker, and Docker Compose

README.md
Update README to indicate that the `./scripts/server` command should be run within the Vagrant VM
Update README.md to clarify that the `./scripts/server' command must be run within the Vagrant VM.
See [README.md](https://github.com/azavea/pfb-network-connectivity/blob/feature/ked/update-readme-run-instructions/README.md)
N/A
=> Minor change to README to clarify run instructions

CHANGELOG.md, src/analysis/import/import_jobs.sh, src/analysis/import/import_neighborhood.sh
The analysis already looks on S3 for cached census data files (jobs and blocks), but there's no facility for actually filling that cache. This makes the analysis scripts that download and use those files also push them up to the S3 cache so they'll be there for the next analysis run. The files don't change (new versions would be released as new files, with a newer year in the filenames), so we don't need to worry about rotating or invalidating the cache.
This is in place of PR #809, which has the advantage of providing a way to load the cache with all the files for all states, but has the disadvantage of adding a lot more code--two Python scripts that are similar but not the same, plus two driver scripts. This achieves the same end as far as what the analysis does--using cached files if …
=> Cache downloaded census data files to S3 within analysis

CHANGELOG.md, README.md, src/django/pfb_analysis/models.py, src/django/pfb_analysis/tests/test_models.py
Ensure that neighborhoods created as part of an AnalysisBatch job are matched with existing neighborhoods, even if they were created by a different user within the organization or if they don't have a fips_code that matches with the existing neighborhood's fips_code. Neighborhoods are now only matched on the fields defined in [unique_together](https://github.com/azavea/pfb-network-connectivity/blob/af9fc26510dfea0ebe806ba5ebc26b952dd55527/src/django/pfb_analysis/models.py#L332). Test cases added to validate AnalysisBatch neighborhood matching logic.
N/A
I'm running into some issues running `./scripts/test` locally, but I am _hopeful_ that the test cases will work as written. I'm continuing to troubleshoot this on my end - I have attached the output logs of this command here for review in …
=> Remove filters for created_by, modified_by and fips_code for Analysis Batch

CHANGELOG.md, src/django/requirements.txt
The base container has gotten some patch version upgrades and dependabot is saying we should upgrade Django. Staying in sync with the base container isn't strictly necessary, but seems like a good plan. So this does that, and adjusts the comment in the requirements file to better describe the situation.
This is lieu of PR #803.
- Run `./scripts/update` to rebuild the containers then `./scripts/server` and make sure the app still works.
- That's probably about as far as we need to go for moving this relatively simple Django app up a few patch versions.
=> Upgrade Django and psycopg2 to match base container

CHANGELOG.md, src/tilegarden/Dockerfile, src/tilegarden/package.json, src/tilegarden/scripts/deploy, src/tilegarden/scripts/deploy-new, src/tilegarden/src/api.js, src/tilegarden/src/tiler.js, src/tilegarden/src/util/param-filter.js, src/tilegarden/yarn.lock
The Tilegarden Lambda function has been running on the Node 8 runtime. Which is fine, except that it's deprecated, so we wouldn't be able to recreate it if something happened to make it break.  Unfortunately Mapnik is not a happy camper on the AWS-provided Node 12 runtime.  It crashes, as described in #801.  As also noted on that issue, there's [an issue on the `node-mapnik` repo](https://github.com/mapnik/node-mapnik/issues/937) where someone got around the problem by using a custom runtime provided by the LambCI project.
So this does the same.  Fortunately
1. LambCI publishes the runtime as versioned layers that you can just add to a Lambda function
2. Claudia.js has a `--layers` option ([as of v5.3](https://claudiajs.com/news/2019/01/07/claudia-5.3.html)) that works with both `create` …
=> Update Tilegarden runtime to node 12 using lambci/node-custom-lambda

README.md, Vagrantfile, deployment/ansible/group_vars/all.example, deployment/ansible/pfb.yml, deployment/ansible/roles.yml, deployment/ansible/roles/pfb.aws-cli/defaults/main.yml, deployment/ansible/roles/pfb.aws-cli/tasks/main.yml
The URL of the 'get-pip.py' script now has a version number, which broke provisioning. In two places, actually, since we need pip at the very beginning to install Ansible inside the VM, then we also had the Azavea `pip` role being used by the Azavea `aws-cli` role.
Having a second place where we install `pip`, especially one that's very simple but not very actively maintained, isn't worth it. So this clones the `aws-cli` role into a local role and drops the dependency on the `pip` role. Since `pip` is installed in the Vagrantfile provisioning, it will always be there.
Also, Ansible still wants to use Python 2 by default, but that's no good. Not that the VM is a user-facing environment, but we already upgraded most of this project and it doesn't make sense to keep using Python 2 if we …
=> Fix pip installation and remove azavea.pip ansible role

CHANGELOG.md, src/analysis/import/import_jobs.sh
Updates the LODES data url in the PFB analysis scripts to pull from 2018 data instead of 2017 data. LODES data should fall back to 2016 if 2018 data is not available.
N/A
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* `./scripts/update`
* Create a new analysis job for an existing neighborhood in the UI
* Run the newly created analysis locally
* Expect to receive a message in stdout indicating that 2018 jobs data has been loaded:
" Downloaded job data file /tmp/tmp.8FTDP8Bevp/import_jobs/co_od_main_JT00_2018.csv.gz from S3"
- [ x ] Add entry to CHANGELOG.md
Resolves #825
=> Update LODES data urls to read 2018 data

CHANGELOG.md, deployment/ansible/pfb.yml, deployment/ansible/roles/pfb.aws-cli/defaults/main.yml, deployment/ansible/roles/pfb.aws-cli/tasks/main.yml, deployment/ansible/roles/pfb.aws-cli2/defaults/main.yml, deployment/ansible/roles/pfb.aws-cli2/tasks/main.yml, scripts/cipublish
- Create AWS cli ansible task to install aws cli 2
- Update aws login command in `cipublish` script to use AWS cli v2
* `./scripts/update`
* SSH into the vm, then
* `export GIT_COMMIT="export GIT_COMMIT=$(git rev-parse --short HEAD)"`
* `export ENVIRONMENT="staging|production"`
* `export PFB_AWS_ECR_ENDPOINT="950872791630.dkr.ecr.us-east-1.amazonaws.com"`
* `./scripts/cibuild`
* `./scripts/cipublish`
- [ x ] Add entry to CHANGELOG.md
Resolves #823
=> Fix docker login command in `cipublish` script

CHANGELOG.md, src/django/pfb_analysis/models.py
In the method that processes batch shapefile uploads, which was updated in PR #814 to look for neighborhoods based on their unique attributes then update their other attributes based on the shapefile, having some neighborhoods with `city_fips` values and some without caused a crash, because the ones without returned `None` as their `city_fips` value, which violates the null constraint of the field.
This adds a check to convert `None` values into empty strings.
Resolves #831
Here's a batch shapefile with one town that has a FIPS code: [WI_and_IA_amesfips.zip](https://github.com/azavea/pfb-network-connectivity/files/5990484/WI_and_IA_amesfips.zip)
The FIPS is 1916900, so if you add a line with that code to your `city_fips_speed.csv` file (download it from …
=> Handle NULL values in city_fips column in batch shapefiles

CHANGELOG.md, Vagrantfile, src/django/pfb_analysis/tasks.py, src/django/pfb_network_connectivity/settings.py
Big imports are timing out and getting killed by Django Q. Also they leave their working files behind when that happens, so when they then get retried dozens of times, the disk ends up full.
To stop all that from happening, this increases the timeout (from 10 minutes to 3 hours) and sets the number of retries at only 1.  (Side note: I can see where "no retries" might not be a good default for a task processing system and any particular number would seem arbitrary, but ["keep retrying until the end of time"](https://django-q.readthedocs.io/en/latest/configure.html#max-attempts) still doesn't seem like the best choice of default behavior to me.)
I don't know what the upper limit is for how long an import could take. I ran one of the imports that failed in production--Oslo, Norway, using …
=> Increase timeout and decrease retries for Django Q tasks; also fix exception handling

CHANGELOG.md, src/analysis/Dockerfile
We've been installing AWS CLI v1 on the analysis container using the "download the bundle and run the install script" method, but that no longer supports older versions of Python. Rebecca emailed with a crash she got when building the analysis container:
Rather than have to upgrade the version of Python we're running in the container, we can just switch to AWS CLI v2, which has no external Python dependency.  The analysis only uses the AWS CLI for simple S3 uploading and downloading, so moving to v2 doesn't require any changes to the commands we're running.
- I also changed `python` to `python3` in the list of apt-get packages to install. It was already getting pulled in by `python3-dev`, but I don't think there's any reason to keep the Python 2 package around, and if there's a place that …
=> Update AWS CLI to v2 to fix unsupported Python error

CHANGELOG.md, Vagrantfile, deployment/ansible/group_vars/all.example, deployment/ansible/roles.yml
VM provisioning has started failing, with a message about Python 3.5 having reached end-of-life. There might be other ways to get around it, but upgrading the base VM would be a good thing anyway, so that's the first thing I tried.
It seems like it worked--I'm able to provision the app and run the analysis. I also updated the Ansible roles for good measure. We only use the VM as a standard environment in which to build and run the containers, so it's not that surprising that it wouldn't be too susceptible to issues from upgrading.
There's a chance this will affect deployment, since we do deployments from within the VM.  But the crash is currently blocking Rebecca from running the analysis locally, and I'm not sure it's worth pursuing the deployment question at the moment, when there are …
=> Update base VM to fix ansible installation error

CHANGELOG.md, src/django/requirements.txt
We have not been able to run migrations in newly built VMs without getting an error. The error gives you a fix, but updating django-q to a recent version stops the error from occurring in the first place.
* Follow the README steps
* You should see no error when running migrations
Resolves #808
=> Update django-q to fix migration error

CHANGELOG.md, deployment/aws-batch/Dockerfile, src/django/pfb_network_connectivity/settings.py, src/verifier/Dockerfile
This PR updates the `EMAIL_BACKEND` in `settings.py` so that it matches the suggested settings in  [`django-amazon-ses v2.1.1`](https://github.com/azavea/django-amazon-ses/tree/2.1.1#django-configuration), since the trackback in the original issue seems to suggest that it ran into module import issue of this dependency, and that this module change in this dep happened in the upgrade of 0.3.2 -> 2.1.1.
This PR also removes `ipython` installation from `deployment/aws-batch/Dockerfile` and `src/verifier/Dockerfile`, and it pins the base image python version in `deployment/aws-batch/Dockerfile`.
* Push a `test/` branch up to trigger a staging deploy
* Once the ECS tasks are cycled, go to https://staging.pfb.azavea.com/#/login/ , click on "Reset password", put in the email address that is …
=> Fix email sending

CHANGELOG.md, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.controller.js, src/angularjs/src/app/analysis-jobs/list/analysis-jobs-list.html, src/angularjs/src/app/components/filters/analysis-job-filter.directive.js, src/angularjs/src/app/components/filters/analysis-job-filter.html, src/django/pfb_analysis/filters.py, src/django/pfb_analysis/serializers.py
Adding the state name makes it easier to distinguish between cities with
the same name. Adding FIPS makes it easier to track cities over time and
stay aligned with other data sources. Both fields are filterable.
* Start the server
* Go to http://localhost:9301/admin#/admin/analysis-jobs/
* Should be searchable by FIPS or state abbreviation
Resolves #865
=> Add State & FIPS cols to admin analysis jobs table (#865)

src/angularjs/bower.json
This also broke the build.
I grepped for SaveAs and couldn't find it used anywhere.
=> Drop unmaintained angular-file-saver

CHANGELOG.md, src/angularjs/src/app/components/places.service.js, src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/app/places/detail/places-detail.html
In the places detail and compare pages, there has been no way to
differentiate between destination types without instances in the given
place and destination types with instances that are inaccessible by low
stress routes. The former are now marked N/A; the latter are marked 0.
* `./scripts/setup`
* `vagrant ssh`
* `./scripts/server`
* if you don't have any places yet when you go to [all places](http://localhost:9301/admin#/places////)
* go to http://localhost:9301/admin#/admin/analysis-jobs/create/batch/ 
* give it a shapefile (feel free to slack me for one)
* go to http://localhost:9301/admin#/places//// and select a place
* for any metric that shows N/A, the associated geojson in your s3 bucket should have 0 features
* for any metric that shows 0, the associated geojson in your s3 …
=> Destination types with no locations are N/A (#867)

Vagrantfile, src/django/pfb_analysis/models.py
Two small fixes for issues I ran into while testing things:
- some of the parameters in the Vagrantfile stopped working when I upgraded to Virtualbox 6
- the analysis job submission wasn't working on staging because the boto client (or the AWS API? comes to the same thing) wants the values in the `environment` parameter to be strings, not numbers.
See the commit messages for a little bit more detail.
I'm not sure how much testing this warrants, but it's worth checking that your VM comes up fine and that you can at least kick off an analysis job.  Testing it again on staging (I didn't test the changed code, but I did test that casting the param to a string made the job submission work in `shell_plus` on the staging instance) probably isn't worth the trouble.
=> Adjust vagrant params and analysis job environment params to fix errors found while testing

deployment/terraform/database.tf, deployment/terraform/variables.tf
The way we specify db parameter group doesn't work well for upgrades.  Removing it is much simpler.
Happy to update and remove terraform-rds entirely as I've done for other projects - this may help with eventually upgrading terraform.
* Confirm stg still works
* Review parameter group values
Resolves #859
=> Drop rds parameter groups as part of db upgrade

CHANGELOG.md, src/analysis/features/speed_limit.sql
Make analysis convert kmph speed limits to rounded mph
```
pfb=# SELECT osm.maxspeed, osm.osm_id FROM neighborhood_osm_full_line osm, neighborhood_ways WHERE neighborhood_ways.osm_id = osm.osm_id                                                         
AND (osm.maxspeed LIKE '% kmph' OR osm.maxspeed ~ '^\d+(\.\d+)?$');
maxspeed |   osm_id   
----------+------------
100      |   13224440
(...and a bunch of other rows...)
pfb=# SELECT osm.maxspeed, osm.osm_id FROM neighborhood_osm_full_line osm, neighborhood_ways WHERE neighborhood_ways.osm_id = osm.osm_id
AND (osm.maxspeed LIKE '% kmph' OR osm.maxspeed ~ '^\d+(\.\d+)?$') AND osm.osm_id=13224440
pfb-# ;
maxspeed |  osm_id  
----------+----------
100      | 13224440
(1 row)
pfb=# SELECT ROUND(substring(osm.maxspeed from '\d+')::INT / 1.609 / …
```
=>  Convert kmph in analysis to mph (#892) 

src/analysis/scripts/download_osm_extract.py, src/angularjs/src/app/analysis-jobs/create/analysis-jobs-create.controller.js
Two small fixes for things I ran into while testing the analysis changes.
1. The OSM extract download script wasn't quite right for US states.  I hadn't noticed because it was using a cached version of the extract from my S3 bucket.  Once I cleared that out, it started producing an error.  The issue is that, whereas the country name in the URL for every other country (as far as I can tell) is the full name (in lower case, with hyphens for spaces), the country name for the US is just "us".  This adds a condition in `download_osm_extract.py` to adjust for that.
2. A couple times I accidentally changed the new "Max Trip Distance" then cleared the field again to let it use the default, but then ended up with a crash because it got a null value rather than the default.  I added a check to the …
=> Apply small fixes from non-US cities analysis testing

src/django/pfb_analysis/management/commands/import_results_shapefiles.py, src/django/pfb_analysis/models.py
A couple fixes for the recent changes to the analysis--one related to the new options, one to the Django upgrade:
1. The new `RUN_IMPORT_JOBS` environment variable for the analysis is a number (0 or 1), which works fine for running the analysis locally but, it turns out, is not OK when sending actual jobs to Batch.  I think this has bitten us once before, and since the values always need to be strings, rather than adjust this one value, I just added a `str()` call to the function that packages the environment variables up for the boto request.
2. The stress network tiles for newly run analysis jobs had some black lines on them.  I had seen them earlier in development, but I thought they were due to stale OSM files, and I thought after I had cleared my OSM cache they went away.  But my …
=> Analysis upgrade fixups

src/analysis/import/import_neighborhood.sh
When downloading a population file from S3, the file gets copied to the temporary directory and needs to be cleaned up, but when using the default local file (`/data/population.zip`) it doesn't, so the `rm` command to remove it after extraction fails.
Also, the command to rename the unzipped files to the default filename is necessary if they're not already named that (e.g. if the file is called `population.zip` but the files inside are called something else), but it crashes if they are.
This changes both commands so they'll still do their thing but will be more tolerant of the files being missing or already named correctly.
This is an alternative to PR #902. I believe it addresses the issue raised there but preserves the cleanup that's needed when the population file is downloaded rather …
=> Fix cleanup commands for non-US population files

CHANGELOG.md, src/angularjs/src/app/components/places.service.js, src/angularjs/src/app/places/compare/compare.html
In PR #879 we changed the front end to show "N/A" when the score for a destination type comes out as zero due to there not being any of that type of destination in the data, as opposed to there being locations but they're 100% inaccessible via low-stress routes. There are in fact cases of the latter, so we couldn't just change all zeroes to "N/A".
This changes the annotation from "N/A" to "No data" and also applies it to the "Employment" line. But since employment isn't a destination type, we couldn't use the same "are there any actual locations?" test to decide whether a value is a true zero or a "no data" situation. Fortunately, there don't appear to be any true zeroes in the analysis jobs that have been run to date--I looked in the production database, and all the zero values were from …
=> Switch 'N/A' to 'No data' and use it when jobs score is zero

CHANGELOG.md, src/analysis/import/import_neighborhood.sh, src/analysis/scripts/download_osm_extract.py, src/django/requirements.txt
This is a grab-bag of three fixes for issues affecting the analysis or the admin views:
Issue #909 
The OSM extract download for places in The United Kingdom of Great Britain and Northern Ireland wasn't working because the package we're using for country names had its short name as "United Kingdom" but the OSM extract URL has it as "great-britain". So this adds a special case.
Issue #910 
The logic for where to get the population file was going wrong because it was using a standard name for non-US population files (`population.zip`) but then both caching it and checking for a cached file under that name.  So the first file to get a `PFB_POP_URL` value downloaded the file and used it as intended, but all subsequent runs were actually ignoring that variable and preferring the …
=> Fixes for UK OSM URL, non-US population file caching, and country search

CHANGELOG.md, src/analysis/import/import_neighborhood.sh, src/django/pfb_analysis/management/commands/load_overall_scores.py
This adds two checks for the situation that caused Milton Keynes to fail during final import and bring the API down with it.  The root of the problem was that there was no population in the imported blocks within the neighborhood boundary, but the way that error manifested was not helpful. It ran the whole analysis and imported the broken score results, then failed because the blank population value caused an error on the database level for any query that tried to load the record.
The two new pieces of error-checking:
- one early in the analysis, as soon as the blocks are imported, so that it will raise a more informative error and avoid running a whole analysis with bad data
- a second in the command that imports analysis results into the database, to raise an error if it encounters an …
=> Raise errors when population is zero

CHANGELOG.md, src/analysis/connectivity/overall_scores.sql
Rebecca reported that the combined scores were getting thrown off for analysis runs with no jobs data, because the zero was getting averaged in rather than skipped.
This adjust the combined scores that the employment score feeds into--the opportunity score, which is a weighted average of employment and education-related scores, and the overall score--to avoid averaging in a zero when we haven't calculated an employment score. The opportunity score also needed divide-by-zero protection after this change, since it makes it possible for all of the components that go into the opportunity score to be absent.
Here's a comparison of three different versions of the same neighborhood ([Tiny Brussels](https://github.com/azavea/pfb-network-connectivity/files/9716343/tiny_brussels.zip)). The one on …
=> Adjust score weights when there's no jobs data

src/angularjs/src/app/places/detail/places-detail.controller.js
From "Crashes" to "Fatal Crashes (2016 - 2020)". The scrollbar overlaps a little with the text but only when it's highlighted.
Resolves #930
=> Change crashes copy in layer picker (#930)

CHANGELOG.md, src/analysis/import/import_jobs.sh
States like Alaska use census data from as far back as 2016. Our current default is 2019, but the import jobs script should recursively attempt prior years. This work stops recursive calls to fetch_census_data from crashing on 404s from the census data endpoint, which was happening when the most current census data for a state was prior to 2018.
* Verify that you can run an analysis job in Alaska
Resolves #934
=> Fix analyses using pre-2018 census data (#934)

src/analysis/connectivity/destinations/dentists.sql, src/analysis/connectivity/destinations/doctors.sql, src/analysis/connectivity/destinations/hospitals.sql, src/analysis/connectivity/destinations/pharmacies.sql, src/analysis/connectivity/destinations/retail.sql, src/analysis/connectivity/destinations/schools.sql, src/analysis/import/pfb.style
Updated dentists, doctors, hospitals, pharmacies, retail, and schools to incorporate alternate or new OSM tags.
=> Update destinations OSM tags

CHANGELOG.md, README.LOCAL-ANALYSIS.md, README.md, Vagrantfile, common.yml, deployment/README.md, deployment/ansible/group_vars/all.example, deployment/ansible/roles/pfb.docker/defaults/main.yml, deployment/ansible/roles/pfb.docker/meta/main.yml, deployment/ansible/roles/pfb.docker/tasks/main.yml, docker-compose.yml, scripts/cibuild, scripts/clear-tile-cache, scripts/console, scripts/django-manage, scripts/infra, scripts/run-local-analysis, scripts/server, scripts/test, scripts/update
Updates the Docker installation to:
- Not use the azavea.docker role (which is no longer maintained), inlining the relevant steps instead.
- Use a newer version
- Invoke Docker Compose with 'docker compose' (rather than 'docker-compose') since that's how it works in newer Docker versions.
I also updated the Vagrant base box, mainly because we might as well not be out of date if we don't have to be, and renamed the shared 'django' docker-compose config to 'django-common', since apparently docker compose now treats it as a name collision to have services in different files with the same name.
Resolves #952
I'm not sure where things stand these days with Vagrant/Virtualbox on Mac machines. Possibly most of these changes won't be relevant.  Though the `docker-compose`->`docker compose` change …
=> Update Docker provisioning and docker compose command

.github/workflows/ci.yml, CHANGELOG.md, deployment/aws-batch/docker-compose.yml
This PR:
- updates the `infra` script to read in AWS creds related env vars
- updates `docker-compose` file used to update job def of batch jobs to pass in the env vars
See the green checkmark of the following GH action job run:
https://github.com/azavea/pfb-network-connectivity/actions/runs/13292649266
Staging ECS tasks were cycled through earlier today
* Push up a `test` branch and let the GH actions pick up the job
* The job should succeed
* A staging deployment should trigger
Resolves #963
=> Fix CI for staging deployment

CHANGELOG.md, docs/SystemComponentsOverview.md
Not much to add here. It's a new file in `docs/` with a high-level (high- to mid-level? mostly high-level) overview of the system components, per issue #960.  Hopefully it's helpful.
=> Add high-level documentation of system components

.github/ISSUE_TEMPLATE/release.md, .github/workflows/deploy_production.yml, src/angularjs/Dockerfile
This PR:
- adds a workaround for an issue reported in [this run](https://github.com/azavea/pfb-network-connectivity/actions/runs/15654091349/job/44102780667) due to a very old Node and Debian version in the angularjs container
- creates release issue template that uses git flow
- includes a github action release workflow for production deployment
* Review the changes and make sure they make sense.
* The newly added GitHub actions release workflow is derived from the [deployment steps](https://github.com/azavea/pfb-network-connectivity/tree/develop/deployment#deploying) and the [ci workflow](https://github.com/azavea/pfb-network-connectivity/blob/develop/.github/workflows/ci.yml).
Resolves https://github.com/azavea/pfb-network-connectivity/issues/965
=> Add production release GitHub action workflow
