azavea/pfb-network-connectivity

deployment/ansible/group_vars/all, deployment/ansible/roles.yml
Fix provisioning by upgrading package versions for postgres and postgis.
=> Update postgres packages

Jenkinsfile, Vagrantfile, docker-compose.test.yml, scripts/cibuild, scripts/test
Add Jenkinsfile to run tests in CI.
Check Jenkins [#6](http://urbanappsci.internal.azavea.com/job/azavea/job/pfb-network-connectivity/view/Pull%20Requests/job/PR-35/6/) and make sure this PR was built successfully.
=> Add cibuild script with Jenkinsfile

README.md
Now set as part of scripts in azavea/pfb#17.
=> Remove output SRID from README

Jenkinsfile
Hopefully the last thing necessary to get an automatic deploy on develop to succeed.
=> Add missing definition of GIT_COMMIT to Jenkinsfile

pfb-analysis/connectivity/census_blocks.sql, pfb-analysis/scripts/run_connectivity.sh
Just discovered a reference to feet in a couple of distance calculations. This PR switches to meters.
=> Fix distance given in feet, switch to meters.

pfb-analysis/import/import_neighborhood.sh
Resolves https://github.com/azavea/pfb-network-connectivity/issues/175#issuecomment-287351927
=> Force 2D on neighborhood geometries during reproject.

src/angularjs/src/app/analysis-jobs/analysis-jobs.constants.js
Intended to be added with #180 refactoring.
=> Add missing Angular constants

src/angularjs/src/app/analysis-jobs/analysis-jobs.constants.js
Missed this additional status in the JS after adding cancelled status in #202
=> Add missing CANCELLED job status

src/angularjs/src/app/index.route.js
Move existing Angular views from site root to /admin.
Closes #193.
* rebuild angularjs container
* views under http://localhost:9301 should all route to http://localhost:9301/admin
=> Move existing views to /admin

src/analysis/connectivity/destinations/retail.sql, src/analysis/scripts/export_connectivity.sh
Export points instead of polygons in GeoJSON outputs. Also adds `geom_pt` column to `neighborhood_retail` table, which is the only of the exported tables without a point column already. Set to centroid of existing polygon column.
<details>
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 2, "blockid10": null, "pop_low_stress": null, "pop_high_stress": null, "pop_score": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -105.17508295247292, 39.955358485732525 ], [ -105.17509087563235, 39.960806646519003 ], [ -105.174943407162885, 39.96082930369564 ], [ -105.174337426400726, 39.960617583957713 ], [ -105.173406626375055, 39.960253720378475 ], [ …
=> Feature/kak/export as points#266

src/analysis/connectivity/access_transit.sql, src/analysis/connectivity/destinations/transit.sql, src/analysis/import/pfb.style, src/analysis/scripts/run_connectivity.sh
Adds transit categories to OSM import and transit-related access measurement scripts.
=> Pull transit data from OSM and add to measures.

src/analysis/scripts/export_connectivity.sh, src/django/pfb_network_connectivity/settings.py
Exports new transit geojson to S3 and makes available in AnalysisJob detail view in admin UI
* Create and run a job all the way through to completion, analysis+tilemaker
* View transit results in AnalysisJob detail view in admin UI
=> Export transit geojson to S3/Admin UI

src/analysis/connectivity/access_overall.sql
Updates weights on access_overall.sql. I missed this in the round of weight changes from earlier today.
=> Update weights on access_overall.sql

src/angularjs/src/app/components/navbar/navbar.html
I forgot to put in the icon-with-name, though I made the controller property to toggle it.  Also, the prototype navbar was a `div`, not a `nav`, and the styles broke a bit when I accidentally switched it.
Here's a screenshot of it cherry-picked onto the neighborhood list branch, where the version of the logo with the name included shows up.
=> Fix styling and icon on navbar

src/angularjs/src/app/components/navbar/navbar.html, src/angularjs/src/app/index.module.js, src/angularjs/src/app/index.route.js, src/angularjs/src/app/login/login.html, src/angularjs/src/app/password-reset/request/password-reset-request.html, src/angularjs/src/app/password-reset/reset/password-reset.html, src/angularjs/src/app/places/list/module.js, src/angularjs/src/app/places/list/place-list.html, src/angularjs/src/app/places/list/places-list.controller.js, src/angularjs/src/app/places/module.js
Implement public neighborhood list view.
Things not done here:
- Show an actual score (data not in neighborhood API response)
- Implement "shape preview" image, whatever that's supposed to be
- Implement sorting/filtering or compare (to be done with #250 and #251)
- Implement section headers grouping by first letter of alphabet (if done, would need to be conditional on sort type and depends on #250)
- Make content available without login (should be public view, but API requires authentication)
Regarding the styling: the navbar seems to overlap the page content somewhat, cutting off the top of the list header.
* At http://localhost:9301/#/places/
* Also should be able to get there via 'All locations' navbar link
* Should list neighborhoods with correct info and working pagination
Closes …
=> Feature/kak/neighborhood angular list#248

common.yml, docker-compose.yml, src/tilemaker/entrypoint.sh, src/tilemaker/scripts/run_tilemaker.sh, src/tilemaker/scripts/utils.sh, src/tilemaker/styles/neighborhood_census_blocks_style.xml, src/tilemaker/styles/neighborhood_ways_style.xml
Updates styling for neighborhood_ways tile layer and adds a neightborhood_census_blocks tile layer.
~The latter runs but produces only blank tiles, I'm not sure why.  Here's the shapefile and the Mapbox Studio Classic project I've been working with.~ Issues resolved. Not sure whether they were entirely projection-related or if I fixed another issue and broke the projection config simultaneously. Anyway, resolved.
That's Glendale, AZ.  I packaged up the tiles and a demo page and put it on the fileshare at `PeopleForBikes_NetworkConnectivity/data/glendale_tile_demo.tar.gz`
Download, extract, change to directory, and run `./run.sh`, and it should launch a local http-server and print the URL to view it at.  (Unless you don't have node installed, in which case it will not do anything useful.) …
=> Generate census block tiles

src/angularjs/src/app/places/list/places-list.controller.js
In public places view, only show those with at least one completed job.
Closes #333.
* http://localhost:9301/#/places/ should only display places that have a score
Connects #333
=> Only show places with a completed job

src/angularjs/src/app/home/home.html
Also modify existing score calculation info section header.
Closes #348.
#344 should modify methodology link added here to point to the methodology page, once added.
* Should display new text on footer correctly
Closes #348
=> Add homepage text on score calculation

src/django/pfb_network_connectivity/settings.py
Quickfix to update the from emails to the correct values. Created #416 to set these via Terraform, but no time for that now.
Trivial, merging for deployment.
=> Update Django default emails

src/angularjs/src/app/home/home.controller.js, src/angularjs/src/app/home/home.html
Adds copy from the doc file in #348 to the home page
@designmatty the images remain unimplemented. I added #411 and assigned to you to address later.
Go to homepage, see text.
=> Add 'How BNA score is calculated' copy

src/angularjs/src/app/places/compare/compare.html, src/angularjs/src/index.html
Fixes:
- Jump to top of methodology page
- Remove duplicate X on compare screen
- Change browser tab title
Ensure the behaviors described above are now correct.
Closes #447, Closes #455, Closes #465
=> Public site grab bag of fixes

src/analysis/import/import_osm.sh
Changes default bike lane width to 5 next to parking, which Fixes a problem with calculating the stress on roads with bike lanes. Must be committed before re-running Boulder and Fort Collins.
=> Changes default lane width to 5

src/angularjs/src/app/home/neighborhood-map.html, src/angularjs/src/styles/components/_card.scss, src/angularjs/src/styles/pages/_home.scss, src/angularjs/src/styles/utils/_variables.scss
Adds a bit more styling to the card over the nationwide map.
Fixes #451
=> styles the nationwide card on homepage

src/angularjs/src/app/components/footer/footer.html, src/angularjs/src/app/components/navbar/navbar.html
=> Tweak feedback link

src/analysis/connectivity/overall_scores.sql
Adds two items to the overall scores table: total miles of high-stress routes and total miles of low-stress routes, derived from neighborhood_ways.
```
id |                 score_id                 | score_original | score_normalized |                                      human_explanation                                      
----+------------------------------------------+----------------+------------------+---------------------------------------------------------------------------------------------
1 | people                                   |         0.2550 |          25.5000 | On average, census blocks in the neighborhood received this population score.
2 | opportunity_employment                   |         0.3048 |          30.4800 | On average, census blocks in the neighborhood …
```
=> Add total high- and low-stress miles to overall scores

src/django/pfb_analysis/management/commands/generate_analysis_csv.py
Forgot to add this, which logs warnings about missing keys and allows execution to continue. 
Going to merge so I can test and deploy to production.
=> Add handling for missing keys in overall_scores

src/angularjs/src/styles/utils/_variables.scss
Add missing semicolon.
Fixes #651.
=> Fix SASS compilation

src/django/pfb_analysis/management/commands/import_results_shapefiles.py
When bulk re-importing jobs, only do so for the latest job for each neighborhood.
Continue in case of failure.
* `./scripts/django-manage import_results_shapefiles`
* Should succeed, only for the latest jobs, with expected logger output
Closes #661.
=> Only reimport latest jobs

src/analysis/features/lanes.sql, src/analysis/import/import_osm.sh
Same as #586, rebased against develop.
=> Rebased: removing pedestrian paths and fixing one-way evaluation

src/analysis/import/import_osm.sh
The analysis on Batch was crashing when trying to write state and city speed limit files to the `/data/` directory.  That's because that directory only exists in development.  This changes it to download the files to a temporary directory, like it does with other downloads.
It still checks for a file at `/data/city_fips_speed.csv` and uses it rather than downloading if it exists.
Here's a local analysis that downloaded the state speed limits but used a local city file:
```
START: Importing State Default Speed Table
CREATE TABLE
2019-02-13 20:34:34 URL:https://s3.amazonaws.com/pfb-public-documents/state_fips_speed.csv [539/539] -> "/tmp$tmp.W0Zv8LB9bF/speed/state_fips_speed.csv" [1]
COPY 51
DONE: Importing state default residential speed
START: Importing City Default Speed Table
CREATE …
```
=> Download speed limit files to temp dir

src/django/pfb_analysis/management/commands/import_results_shapefiles.py
When importing a shapefile, the job ID should always be set to the job we're importing it for.  We've hit a few different issues from missing or mis-matched job IDs in input shapefiles, but we can just ignore the value (or lack thereof) in the shapefile completely and set it to the target job ID after import.
So this does that. Since there doesn't seem to be a way to set the value of a field to a literal string via the layer mapping, this relies (as we were doing before in the event of job id errors) on setting the job ID after import on all geometries with no job ID.  Since this could theoretically cause an issue if multiple imports were running simultaneously, this puts the import in a transaction so there won't ever be ID-less geometries actually committed to the database.
This also …
=> Ignore job ID in imported shapefiles

CHANGELOG.md, src/angularjs/src/app/index.config.js, src/angularjs/src/app/index.route.js, src/angularjs/src/app/neighborhoods/create/module.js, src/angularjs/src/app/neighborhoods/detail/module.js, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.controller.js, src/angularjs/src/app/neighborhoods/detail/neighborhoods-detail.html, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.controller.js, src/angularjs/src/app/neighborhoods/list/neighborhoods-list.html, src/angularjs/src/app/neighborhoods/module.js, src/django/pfb_analysis/views.py
Adds the ability to edit neighborhood details, by converting the "Create" view into a "Create/Edit" view--if there's a UUID in the path it edits that neighborhood, if not it creates a new one.
I had planned to include the boundary file as an optional editable field--i.e. if it was provided, it would replace the current boundary, but if omitted the boundary would be left as-is--but when I had the field in there, uploading a different file wasn't having the effect of actually changing the boundary.  So I think that requires some additional handling.  The pieces are probably mostly in place, since we replace boundaries when running batch uploads, but I think it makes sense to spin it off into a separate issue (and possibly to do it in conjunction with #767, since having a preview would make …
=> Enable editing neighborhood details

src/angularjs/src/app/leaflet/map-speed-limit-legend.control.js, src/angularjs/src/styles/components/_map.scss
Quick styling pass on the speed limit indicator over the map.
**Before**
**After**
=> updates the styling for speed limit on the map

README.md, docker-compose.yml, scripts/update
With new docker on Jenkins the upgrade to postgres 13 just worked.
Also adding how to do a Jenkins like setup locally - which isn't as useful as Vagrant *yet*, but maybe a good target for the future?
Other README changes are just from automarkdown.
=> Upgrade to Posgres 13

deployment/terraform/variables.tf
Newer bastion is working fine so far.
* ssh-add key as usual
* ssh ec2-user@bastion.staging.pfb.azavea.com
=> Update bastion to modern version
